(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Branch_with_protection.t : Branch With Protection
 *)

type t = {
  name : string;
  commit : Commit.t;
  _links : Branch_with_protection__links.t;
  protected : bool;
  protection : Branch_protection.t;
  protection_url : string;
  pattern : string option; [@default None]
  required_approving_review_count : int32 option; [@default None]
}
[@@deriving yojson { strict = false }, show]

(** Branch With Protection *)
let create (name : string) (commit : Commit.t)
    (_links : Branch_with_protection__links.t) (protected : bool)
    (protection : Branch_protection.t) (protection_url : string) : t =
  {
    name;
    commit;
    _links;
    protected;
    protection;
    protection_url;
    pattern = None;
    required_approving_review_count = None;
  }
