(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  metadata : string option; [@default None]
  contents : string option; [@default None]
  issues : string option; [@default None]
  single_file : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  { metadata = None; contents = None; issues = None; single_file = None }
