(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  auto_trigger_checks :
    Check_suite_preference_preferences_auto_trigger_checks.t list;
}
[@@deriving yojson { strict = false }, show]

let create () : t = { auto_trigger_checks = [] }
