(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Email.t : Email
 *)

type t = {
  email : string;
  primary : bool;
  verified : bool;
  visibility : string option;
}
[@@deriving yojson { strict = false }, show]

(** Email *)
let create (email : string) (primary : bool) (verified : bool)
    (visibility : string option) : t =
  { email; primary; verified; visibility }
