(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  href : string option; [@default None]
  _type : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t = { href = None; _type = None }
