(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  path : string option; [@default None]
  mode : string option; [@default None]
  _type : string option; [@default None]
  sha : string option; [@default None]
  size : int32 option; [@default None]
  url : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    path = None;
    mode = None;
    _type = None;
    sha = None;
    size = None;
    url = None;
  }
