(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Hovercard.t : Hovercard
 *)

type t = { contexts : Hovercard_contexts.t list }
[@@deriving yojson { strict = false }, show]

(** Hovercard *)
let create (contexts : Hovercard_contexts.t list) : t = { contexts }
