(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  message : string option; [@default None]
  errors : Inline_response_422_1_errors.t list;
  documentation_url : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t = { message = None; errors = []; documentation_url = None }
