(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The title of the new pull request. *)
  title : string option; [@default None]
  (* The name of the branch where your changes are implemented. For cross-repository pull requests in the same network, namespace `head` with a user like this: `username:branch`. *)
  head : string;
  (* The name of the branch you want the changes pulled into. This should be an existing branch on the current repository. You cannot submit a pull request to one repository that requests a merge to a base of another repository. *)
  base : string;
  (* The contents of the pull request. *)
  body : string option; [@default None]
  (* Indicates whether [maintainers can modify](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) the pull request. *)
  maintainer_can_modify : bool option; [@default None]
  (* Indicates whether the pull request is a draft. See \''[Draft Pull Requests](https://help.github.com/en/articles/about-pull-requests#draft-pull-requests)\'' in the GitHub Help documentation to learn more. *)
  draft : bool option; [@default None]
  issue : int32 option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create (head : string) (base : string) : t =
  {
    title = None;
    head;
    base;
    body = None;
    maintainer_can_modify = None;
    draft = None;
    issue = None;
  }
