(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Describes the last point that notifications were checked. *)
  last_read_at : string option; [@default None]
  (* Whether the notification has been read. *)
  read : bool option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t = { last_read_at = None; read = None }
