(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The reason for locking the issue or pull request conversation. Lock will fail if you don't use one of these reasons:   \\* `off-topic`   \\* `too heated`   \\* `resolved`   \\* `spam` *)
  lock_reason : Enums.lock_reason option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t = { lock_reason = None }
