(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Value for your secret, encrypted with [LibSodium](https://libsodium.gitbook.io/doc/bindings_for_other_languages) using the public key retrieved from the [Get a repository public key](https://docs.github.com/enterprise-server@2.22/rest/reference/actions#get-a-repository-public-key) endpoint. *)
  encrypted_value : string option; [@default None]
  (* ID of the key you used to encrypt the secret. *)
  key_id : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t = { encrypted_value = None; key_id = None }
