(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The new pre-receive environment's name. *)
  name : string;
  (* URL from which to download a tarball of this environment. *)
  image_url : string;
}
[@@deriving yojson { strict = false }, show]

let create (name : string) (image_url : string) : t = { name; image_url }
