(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The name of the hook. *)
  name : string option; [@default None]
  (* The script that the hook runs. *)
  script : string option; [@default None]
  (* The GitHub repository where the script is kept. *)
  script_repository : (string * Yojson.Safe.t) list;
  (* The pre-receive environment where the script is executed. *)
  environment : (string * Yojson.Safe.t) list;
  (* The state of enforcement for this hook. *)
  enforcement : string option; [@default None]
  (* Whether enforcement can be overridden at the org or repo level. *)
  allow_downstream_configuration : bool option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    name = None;
    script = None;
    script_repository = [];
    environment = [];
    enforcement = None;
    allow_downstream_configuration = None;
  }
