(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Model__repos__owner___repo__branches__branch__protection_required_status_checks.t : Require status checks to pass before merging. Set to `null` to disable.
 *)

type t = {
  (* Require branches to be up to date before merging. *)
  strict : bool;
  (* The list of status checks to require in order to merge into this branch *)
  contexts : string list;
}
[@@deriving yojson { strict = false }, show]

(** Require status checks to pass before merging. Set to `null` to disable. *)
let create (strict : bool) (contexts : string list) : t = { strict; contexts }
