(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The relative path to the file that necessitates a review comment. *)
  path : string;
  (* The position in the diff where you want to add a review comment. Note this value is not the same as the line number in the file. For help finding the position value, read the note below. *)
  position : int32 option; [@default None]
  (* Text of the review comment. *)
  body : string;
  line : int32 option; [@default None]
  side : string option; [@default None]
  start_line : int32 option; [@default None]
  start_side : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create (path : string) (body : string) : t =
  {
    path;
    position = None;
    body;
    line = None;
    side = None;
    start_line = None;
    start_side = None;
  }
