(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The list of users with review dismissal access. *)
  users : Simple_user.t list;
  (* The list of teams with review dismissal access. *)
  teams : Team.t list;
  url : string option; [@default None]
  users_url : string option; [@default None]
  teams_url : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  { users = []; teams = []; url = None; users_url = None; teams_url = None }
