(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  label : string;
  ref : string;
  repo : Repository.t;
  sha : string;
  user : Simple_user.t option;
}
[@@deriving yojson { strict = false }, show]

let create (label : string) (ref : string) (repo : Repository.t) (sha : string)
    (user : Simple_user.t option) : t =
  { label; ref; repo; sha; user }
