(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Repository_collaborator_permission.t : Repository Collaborator Permission
 *)

type t = { permission : string; user : Simple_user.t option }
[@@deriving yojson { strict = false }, show]

(** Repository Collaborator Permission *)
let create (permission : string) (user : Simple_user.t option) : t =
  { permission; user }
