(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* A unique identifier for the rule used to detect the alert. *)
  id : string option; [@default None]
  (* The severity of the alert. *)
  severity : Enums.severity option; [@default None]
  (* A short description of the rule used to detect the alert. *)
  description : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t = { id = None; severity = None; description = None }
