(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Combined_commit_status.t : Combined Commit Status
 *)

type t = {
  state : string;
  statuses : Simple_commit_status.t list;
  sha : string;
  total_count : int32;
  repository : Minimal_repository.t;
  commit_url : string;
  url : string;
}
[@@deriving yojson { strict = false }, show]

(** Combined Commit Status *)
let create (state : string) (statuses : Simple_commit_status.t list)
    (sha : string) (total_count : int32) (repository : Minimal_repository.t)
    (commit_url : string) (url : string) : t =
  { state; statuses; sha; total_count; repository; commit_url; url }
