(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  sha : string option; [@default None]
  node_id : string option; [@default None]
  url : string option; [@default None]
  html_url : string option; [@default None]
  author : File_commit_commit_author.t option; [@default None]
  committer : File_commit_commit_author.t option; [@default None]
  message : string option; [@default None]
  tree : File_commit_commit_tree.t option; [@default None]
  parents : File_commit_commit_parents.t list;
  verification : File_commit_commit_verification.t option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    sha = None;
    node_id = None;
    url = None;
    html_url = None;
    author = None;
    committer = None;
    message = None;
    tree = None;
    parents = [];
    verification = None;
  }
