(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Git_ref.t : Git references within a repository
 *)

type t = {
  ref : string option; [@default None]
  node_id : string option; [@default None]
  url : string option; [@default None]
  _object : Git_ref_object.t option; [@default None]
}
[@@deriving yojson { strict = false }, show]

(** Git references within a repository *)
let create () : t = { ref = None; node_id = None; url = None; _object = None }
