(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Organization_simple.t : Organization Simple
 *)

type t = {
  login : string;
  id : int32;
  node_id : string;
  url : string;
  repos_url : string;
  events_url : string;
  hooks_url : string;
  issues_url : string;
  members_url : string;
  public_members_url : string;
  avatar_url : string;
  description : string option;
}
[@@deriving yojson { strict = false }, show]

(** Organization Simple *)
let create (login : string) (id : int32) (node_id : string) (url : string)
    (repos_url : string) (events_url : string) (hooks_url : string)
    (issues_url : string) (members_url : string) (public_members_url : string)
    (avatar_url : string) (description : string option) : t =
  {
    login;
    id;
    node_id;
    url;
    repos_url;
    events_url;
    hooks_url;
    issues_url;
    members_url;
    public_members_url;
    avatar_url;
    description;
  }
