(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = { url : string; enabled : bool }
[@@deriving yojson { strict = false }, show]

let create (url : string) (enabled : bool) : t = { url; enabled }
