(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  self : Pull_request_review_comment__links_self.t;
  html : Pull_request_review_comment__links_html.t;
  pull_request : Pull_request_review_comment__links_pull_request.t;
}
[@@deriving yojson { strict = false }, show]

let create (self : Pull_request_review_comment__links_self.t)
    (html : Pull_request_review_comment__links_html.t)
    (pull_request : Pull_request_review_comment__links_pull_request.t) : t =
  { self; html; pull_request }
