(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Rate_limit_overview.t : Rate Limit Overview
 *)

type t = { resources : Rate_limit_overview_resources.t; rate : Rate_limit.t }
[@@deriving yojson { strict = false }, show]

(** Rate Limit Overview *)
let create (resources : Rate_limit_overview_resources.t) (rate : Rate_limit.t) :
    t =
  { resources; rate }
