(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Thread_subscription.t : Thread Subscription
 *)

type t = {
  subscribed : bool;
  ignored : bool;
  reason : string option;
  created_at : string option;
  url : string;
  thread_url : string option; [@default None]
  repository_url : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

(** Thread Subscription *)
let create (subscribed : bool) (ignored : bool) (reason : string option)
    (created_at : string option) (url : string) : t =
  {
    subscribed;
    ignored;
    reason;
    created_at;
    url;
    thread_url = None;
    repository_url = None;
  }
