(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val search_code :
  q:string ->
  ?sort:Enums.sort_3 ->
  ?order:Enums.order ->
  ?per_page:int32 ->
  ?page:int32 ->
  unit ->
  Inline_response_200_17.t Lwt.t

val search_commits :
  q:string ->
  ?sort:Enums.sort_2 ->
  ?order:Enums.order ->
  ?per_page:int32 ->
  ?page:int32 ->
  unit ->
  Inline_response_200_18.t Lwt.t

val search_issues_and_pull_requests :
  q:string ->
  ?sort:Enums.sort_5 ->
  ?order:Enums.order ->
  ?per_page:int32 ->
  ?page:int32 ->
  unit ->
  Inline_response_200_19.t Lwt.t

val search_labels :
  repository_id:int32 ->
  q:string ->
  ?sort:Enums.sort_7 ->
  ?order:Enums.order ->
  unit ->
  Inline_response_200_20.t Lwt.t

val search_repos :
  q:string ->
  ?sort:Enums.sort_9 ->
  ?order:Enums.order ->
  ?per_page:int32 ->
  ?page:int32 ->
  unit ->
  Inline_response_200_21.t Lwt.t

val search_topics : q:string -> Inline_response_200_22.t Lwt.t

val search_users :
  q:string ->
  ?sort:Enums.sort_0 ->
  ?order:Enums.order ->
  ?per_page:int32 ->
  ?page:int32 ->
  unit ->
  Inline_response_200_23.t Lwt.t
