(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    bacs_debit_payments: Account_bacs_debit_payments_settings.t option [@default None];
    branding: Account_branding_settings.t;
    card_payments: Account_card_payments_settings.t;
    dashboard: Account_dashboard_settings.t;
    payments: Account_payments_settings.t;
    payouts: Account_payout_settings.t option [@default None];
    sepa_debit_payments: Account_sepa_debit_payments_settings.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (branding : Account_branding_settings.t) (card_payments : Account_card_payments_settings.t) (dashboard : Account_dashboard_settings.t) (payments : Account_payments_settings.t) : t = {
    bacs_debit_payments = None;
    branding = branding;
    card_payments = card_payments;
    dashboard = dashboard;
    payments = payments;
    payouts = None;
    sepa_debit_payments = None;
}

