(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Unique identifier for the object. *)
    id: string;
    (* The name of the application. *)
    name: string option [@default None];
    (* String representing the object's type. Objects of the same type share the same value. *)
    _object: Enums.application_object[@default `Application];
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (_object : Enums.application_object) : t = {
    id = id;
    name = None;
    _object = _object;
}

