(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Capability.t : This is an object representing a capability for a Stripe account.  Related guide: [Account capabilities](https://stripe.com/docs/connect/account-capabilities).
 *)

type t = {
    (* The account for which the capability enables functionality. *)
    account: Any_ofstringaccount.t;
    (* The identifier for the capability. *)
    id: string;
    (* String representing the object's type. Objects of the same type share the same value. *)
    _object: Enums.capability_object[@default `Capability];
    (* Whether the capability has been requested. *)
    requested: bool;
    (* Time at which the capability was requested. Measured in seconds since the Unix epoch. *)
    requested_at: int32 option [@default None];
    requirements: Account_capability_requirements.t option [@default None];
    (* The status of the capability. Can be `active`, `inactive`, `pending`, or `unrequested`. *)
    status: Enums.capability_status;
} [@@deriving yojson { strict = false }, show ];;

(** This is an object representing a capability for a Stripe account.  Related guide: [Account capabilities](https://stripe.com/docs/connect/account-capabilities). *)
let create (account : Any_ofstringaccount.t) (id : string) (_object : Enums.capability_object) (requested : bool) (status : Enums.capability_status) : t = {
    account = account;
    id = id;
    _object = _object;
    requested = requested;
    requested_at = None;
    requirements = None;
    status = status;
}

