(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Country_spec.t : Stripe needs to collect certain pieces of information about each account created. These requirements can differ depending on the account's country. The Country Specs API makes these rules available to your integration.  You can also view the information from this API call as [an online guide](/docs/connect/required-verification-information).
 *)

type t = {
    (* The default currency for this country. This applies to both payment methods and bank accounts. *)
    default_currency: string;
    (* Unique identifier for the object. Represented as the ISO country code for this country. *)
    id: string;
    (* String representing the object's type. Objects of the same type share the same value. *)
    _object: Enums.country_spec_object[@default `Country_spec];
    (* Currencies that can be accepted in the specific country (for transfers). *)
    supported_bank_account_currencies: (string * string list) list;
    (* Currencies that can be accepted in the specified country (for payments). *)
    supported_payment_currencies: string list;
    (* Payment methods available in the specified country. You may need to enable some payment methods (e.g., [ACH](https://stripe.com/docs/ach)) on your account before they appear in this list. The `stripe` payment method refers to [charging through your platform](https://stripe.com/docs/connect/destination-charges). *)
    supported_payment_methods: string list;
    (* Countries that can accept transfers from the specified country. *)
    supported_transfer_countries: string list;
    verification_fields: Country_spec_verification_fields.t;
} [@@deriving yojson { strict = false }, show ];;

(** Stripe needs to collect certain pieces of information about each account created. These requirements can differ depending on the account's country. The Country Specs API makes these rules available to your integration.  You can also view the information from this API call as [an online guide](/docs/connect/required-verification-information). *)
let create (default_currency : string) (id : string) (_object : Enums.country_spec_object) (supported_bank_account_currencies : (string * string list) list) (supported_payment_currencies : string list) (supported_payment_methods : string list) (supported_transfer_countries : string list) (verification_fields : Country_spec_verification_fields.t) : t = {
    default_currency = default_currency;
    id = id;
    _object = _object;
    supported_bank_account_currencies = supported_bank_account_currencies;
    supported_payment_currencies = supported_payment_currencies;
    supported_payment_methods = supported_payment_methods;
    supported_transfer_countries = supported_transfer_countries;
    verification_fields = verification_fields;
}

