(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be `null` for subscription schedules where `billing=charge_automatically`. *)
    days_until_due: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    days_until_due = None;
}

