(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Invoice_lines_list_1.t : The individual line items that make up the invoice. `lines` is sorted as follows: invoice items in reverse chronological order, followed by the subscription, if any.
 *)

type t = {
    (* Details about each object. *)
    data: Line_item.t list;
    (* True if this list has another page of items after this one that can be fetched. *)
    has_more: bool;
    (* String representing the object's type. Objects of the same type share the same value. Always has the value `list`. *)
    _object: Enums.listaccountcapability_object[@default `List];
    (* The URL where this list can be accessed. *)
    url: string;
} [@@deriving yojson { strict = false }, show ];;

(** The individual line items that make up the invoice. `lines` is sorted as follows: invoice items in reverse chronological order, followed by the subscription, if any. *)
let create (data : Line_item.t list) (has_more : bool) (_object : Enums.listaccountcapability_object) (url : string) : t = {
    data = data;
    has_more = has_more;
    _object = _object;
    url = url;
}

