(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* (ID of a [file upload](https://stripe.com/docs/guides/file-upload)) Additional documentation supporting the dispute. *)
    additional_documentation: Any_ofstringfile.t option [@default None];
    (* Explanation of why the cardholder is disputing this transaction. *)
    explanation: string option [@default None];
    (* Date when the product was received. *)
    received_at: int32 option [@default None];
    (* Description of the cardholder's attempt to return the product. *)
    return_description: string option [@default None];
    (* Result of cardholder's attempt to return the product. *)
    return_status: Enums.return_status option [@default None];
    (* Date when the product was returned or attempted to be returned. *)
    returned_at: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    additional_documentation = None;
    explanation = None;
    received_at = None;
    return_description = None;
    return_status = None;
    returned_at = None;
}

