(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* An identifying document, either a passport or local ID card. *)
    document: Any_ofissuing_cardholder_id_document.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    document = None;
}

