(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Maximum amount allowed to spend per interval. *)
    amount: int32;
    (* Array of strings containing [categories](https://stripe.com/docs/api#issuing_authorization_object-merchant_data-category) this limit applies to. Omitting this field will apply the limit to all categories. *)
    categories: Enums.allowed_categories list;
    (* Interval (or event) to which the amount applies. *)
    interval: Enums.issuing_card_spending_limit_interval;
} [@@deriving yojson { strict = false }, show ];;

let create (amount : int32) (interval : Enums.issuing_card_spending_limit_interval) : t = {
    amount = amount;
    categories = [];
    interval = interval;
}

