(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Array of strings containing [categories](https://stripe.com/docs/api#issuing_authorization_object-merchant_data-category) of authorizations to allow. All other categories will be blocked. Cannot be set with `blocked_categories`. *)
    allowed_categories: Enums.allowed_categories list;
    (* Array of strings containing [categories](https://stripe.com/docs/api#issuing_authorization_object-merchant_data-category) of authorizations to decline. All other categories will be allowed. Cannot be set with `allowed_categories`. *)
    blocked_categories: Enums.allowed_categories list;
    (* Limit spending with amount-based rules that apply across this cardholder's cards. *)
    spending_limits: Issuing_cardholder_spending_limit.t list;
    (* Currency of the amounts within `spending_limits`. *)
    spending_limits_currency: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    allowed_categories = [];
    blocked_categories = [];
    spending_limits = [];
    spending_limits_currency = None;
}

