(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    address: Address.t option [@default None];
    (* The Kana variation of the company's primary address (Japan only). *)
    address_kana: Any_oflegal_entity_japan_address.t option [@default None];
    (* The Kanji variation of the company's primary address (Japan only). *)
    address_kanji: Any_oflegal_entity_japan_address.t option [@default None];
    (* Whether the company's directors have been provided. This Boolean will be `true` if you've manually indicated that all directors are provided via [the `directors_provided` parameter](https://stripe.com/docs/api/accounts/update#update_account-company-directors_provided). *)
    directors_provided: bool option [@default None];
    (* Whether the company's executives have been provided. This Boolean will be `true` if you've manually indicated that all executives are provided via [the `executives_provided` parameter](https://stripe.com/docs/api/accounts/update#update_account-company-executives_provided), or if Stripe determined that sufficient executives were provided. *)
    executives_provided: bool option [@default None];
    (* The company's legal name. *)
    name: string option [@default None];
    (* The Kana variation of the company's legal name (Japan only). *)
    name_kana: string option [@default None];
    (* The Kanji variation of the company's legal name (Japan only). *)
    name_kanji: string option [@default None];
    (* Whether the company's owners have been provided. This Boolean will be `true` if you've manually indicated that all owners are provided via [the `owners_provided` parameter](https://stripe.com/docs/api/accounts/update#update_account-company-owners_provided), or if Stripe determined that sufficient owners were provided. Stripe determines ownership requirements using both the number of owners provided and their total percent ownership (calculated by adding the `percent_ownership` of each owner together). *)
    owners_provided: bool option [@default None];
    (* The company's phone number (used for verification). *)
    phone: string option [@default None];
    (* The category identifying the legal structure of the company or legal entity. See [Business structure](https://stripe.com/docs/connect/identity-verification#business-structure) for more details. *)
    structure: Enums.legal_entity_company_structure option [@default None];
    (* Whether the company's business ID number was provided. *)
    tax_id_provided: bool option [@default None];
    (* The jurisdiction in which the `tax_id` is registered (Germany-based companies only). *)
    tax_id_registrar: string option [@default None];
    (* Whether the company's business VAT number was provided. *)
    vat_id_provided: bool option [@default None];
    (* Information on the verification state of the company. *)
    verification: Any_oflegal_entity_company_verification.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    address = None;
    address_kana = None;
    address_kanji = None;
    directors_provided = None;
    executives_provided = None;
    name = None;
    name_kana = None;
    name_kanji = None;
    owners_provided = None;
    phone = None;
    structure = None;
    tax_id_provided = None;
    tax_id_registrar = None;
    vat_id_provided = None;
    verification = None;
}

