(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* City/Ward. *)
    city: string option [@default None];
    (* Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)). *)
    country: string option [@default None];
    (* Block/Building number. *)
    line1: string option [@default None];
    (* Building details. *)
    line2: string option [@default None];
    (* ZIP or postal code. *)
    postal_code: string option [@default None];
    (* Prefecture. *)
    state: string option [@default None];
    (* Town/cho-me. *)
    town: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    city = None;
    country = None;
    line1 = None;
    line2 = None;
    postal_code = None;
    state = None;
    town = None;
}

