(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Bank code of bank associated with the bank account. *)
    bank_code: string option [@default None];
    (* Name of the bank associated with the bank account. *)
    bank_name: string option [@default None];
    (* Bank Identifier Code of the bank associated with the bank account. *)
    bic: string option [@default None];
    (* Owner's verified full name. Values are verified or provided by Giropay directly (if supported) at the time of authorization or settlement. They cannot be set or mutated. Giropay rarely provides this information so the attribute is usually empty. *)
    verified_name: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    bank_code = None;
    bank_name = None;
    bic = None;
    verified_name = None;
}

