(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Bank-State-Branch number of the bank account. *)
    bsb_number: string option [@default None];
    (* Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same. *)
    fingerprint: string option [@default None];
    (* Last four digits of the bank account number. *)
    last4: string option [@default None];
    (* ID of the mandate used to make this payment. *)
    mandate: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    bsb_number = None;
    fingerprint = None;
    last4 = None;
    mandate = None;
}

