(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Radar_value_list.t : Value lists allow you to group values together which can then be referenced in rules.  Related guide: [Default Stripe Lists](https://stripe.com/docs/radar/lists#managing-list-items).
 *)

type t = {
    (* The name of the value list for use in rules. *)
    alias: string;
    (* Time at which the object was created. Measured in seconds since the Unix epoch. *)
    created: int32;
    (* The name or email address of the user who created this value list. *)
    created_by: string;
    (* Unique identifier for the object. *)
    id: string;
    (* The type of items in the value list. One of `card_fingerprint`, `card_bin`, `email`, `ip_address`, `country`, `string`, or `case_sensitive_string`. *)
    item_type: Enums.item_type;
    list_items: Radar_list_list_item_list.t;
    (* Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode. *)
    livemode: bool;
    (* Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. *)
    metadata: (string * string) list;
    (* The name of the value list. *)
    name: string;
    (* String representing the object's type. Objects of the same type share the same value. *)
    _object: Enums.deleted_radar_value_list_object[@default `RadarPeriodvalue_list];
} [@@deriving yojson { strict = false }, show ];;

(** Value lists allow you to group values together which can then be referenced in rules.  Related guide: [Default Stripe Lists](https://stripe.com/docs/radar/lists#managing-list-items). *)
let create (alias : string) (created : int32) (created_by : string) (id : string) (item_type : Enums.item_type) (list_items : Radar_list_list_item_list.t) (livemode : bool) (metadata : (string * string) list) (name : string) (_object : Enums.deleted_radar_value_list_object) : t = {
    alias = alias;
    created = created;
    created_by = created_by;
    id = id;
    item_type = item_type;
    list_items = list_items;
    livemode = livemode;
    metadata = metadata;
    name = name;
    _object = _object;
}

