(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Recipient.t : With `Recipient` objects, you can transfer money from your Stripe account to a third-party bank account or debit card. The API allows you to create, delete, and update your recipients. You can retrieve individual recipients as well as a list of all your recipients.  **`Recipient` objects have been deprecated in favor of [Connect](https://stripe.com/docs/connect), specifically Connect's much more powerful [Account objects](https://stripe.com/docs/api#account). Stripe accounts that don't already use recipients can no longer begin doing so. Please use `Account` objects instead.**
 *)

type t = {
    (* Hash describing the current account on the recipient, if there is one. *)
    active_account: Any_ofbank_account.t option [@default None];
    cards: Card_list_1.t option [@default None];
    (* Time at which the object was created. Measured in seconds since the Unix epoch. *)
    created: int32;
    (* The default card to use for creating transfers to this recipient. *)
    default_card: Any_ofstringcard.t option [@default None];
    (* An arbitrary string attached to the object. Often useful for displaying to users. *)
    description: string option [@default None];
    email: string option [@default None];
    (* Unique identifier for the object. *)
    id: string;
    (* Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode. *)
    livemode: bool;
    (* Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. *)
    metadata: (string * string) list;
    (* The ID of the [Custom account](https://stripe.com/docs/connect/custom-accounts) this recipient was migrated to. If set, the recipient can no longer be updated, nor can transfers be made to it: use the Custom account instead. *)
    migrated_to: Any_ofstringaccount.t option [@default None];
    (* Full, legal name of the recipient. *)
    name: string option [@default None];
    (* String representing the object's type. Objects of the same type share the same value. *)
    _object: Enums.deleted_recipient_object[@default `Recipient];
    rolled_back_from: Any_ofstringaccount.t option [@default None];
    (* Type of the recipient, one of `individual` or `corporation`. *)
    _type: string;
} [@@deriving yojson { strict = false }, show ];;

(** With `Recipient` objects, you can transfer money from your Stripe account to a third-party bank account or debit card. The API allows you to create, delete, and update your recipients. You can retrieve individual recipients as well as a list of all your recipients.  **`Recipient` objects have been deprecated in favor of [Connect](https://stripe.com/docs/connect), specifically Connect's much more powerful [Account objects](https://stripe.com/docs/api#account). Stripe accounts that don't already use recipients can no longer begin doing so. Please use `Account` objects instead.** *)
let create (created : int32) (id : string) (livemode : bool) (metadata : (string * string) list) (_object : Enums.deleted_recipient_object) (_type : string) : t = {
    active_account = None;
    cards = None;
    created = created;
    default_card = None;
    description = None;
    email = None;
    id = id;
    livemode = livemode;
    metadata = metadata;
    migrated_to = None;
    name = None;
    _object = _object;
    rolled_back_from = None;
    _type = _type;
}

