(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    bank_code: string option [@default None];
    bank_name: string option [@default None];
    bic: string option [@default None];
    country: string option [@default None];
    iban_last4: string option [@default None];
    preferred_language: string option [@default None];
    statement_descriptor: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    bank_code = None;
    bank_name = None;
    bic = None;
    country = None;
    iban_last4 = None;
    preferred_language = None;
    statement_descriptor = None;
}

