(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Bank account fingerprint associated with the Stripe owned bank account receiving the transfer. *)
    fingerprint: string option [@default None];
    (* The credit transfer rails the sender used to push this transfer. The possible rails are: Faster Payments, BACS, CHAPS, and wire transfers. Currently only Faster Payments is supported. *)
    funding_method: string option [@default None];
    (* Last 4 digits of sender account number associated with the transfer. *)
    last4: string option [@default None];
    (* Sender entered arbitrary information about the transfer. *)
    reference: string option [@default None];
    (* Sender account number associated with the transfer. *)
    sender_account_number: string option [@default None];
    (* Sender name associated with the transfer. *)
    sender_name: string option [@default None];
    (* Sender sort code associated with the transfer. *)
    sender_sort_code: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    fingerprint = None;
    funding_method = None;
    last4 = None;
    reference = None;
    sender_account_number = None;
    sender_name = None;
    sender_sort_code = None;
}

