(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The time that the order was canceled. *)
    canceled: int32 option [@default None];
    (* The time that the order was fulfilled. *)
    fulfiled: int32 option [@default None];
    (* The time that the order was paid. *)
    paid: int32 option [@default None];
    (* The time that the order was returned. *)
    returned: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    canceled = None;
    fulfiled = None;
    paid = None;
    returned = None;
}

