(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Specifies invoicing frequency. Either `day`, `week`, `month` or `year`. *)
    interval: Enums.interval;
    (* The number of intervals between invoices. For example, `interval=month` and `interval_count=3` bills every 3 months. Maximum of one year interval allowed (1 year, 12 months, or 52 weeks). *)
    interval_count: int32;
} [@@deriving yojson { strict = false }, show ];;

let create (interval : Enums.interval) (interval_count : int32) : t = {
    interval = interval;
    interval_count = interval_count;
}

