(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Tax_id.t : You can add one or multiple tax IDs to a [customer](https://stripe.com/docs/api/customers). A customer's tax IDs are displayed on invoices and credit notes issued for the customer.  Related guide: [Customer Tax Identification Numbers](https://stripe.com/docs/billing/taxes/tax-ids).
 *)

type t = {
    (* Two-letter ISO code representing the country of the tax ID. *)
    country: string option [@default None];
    (* Time at which the object was created. Measured in seconds since the Unix epoch. *)
    created: int32;
    (* ID of the customer. *)
    customer: Any_ofstringcustomer.t option [@default None];
    (* Unique identifier for the object. *)
    id: string;
    (* Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode. *)
    livemode: bool;
    (* String representing the object's type. Objects of the same type share the same value. *)
    _object: Enums.deleted_tax_id_object[@default `Tax_id];
    (* Type of the tax ID, one of `ae_trn`, `au_abn`, `br_cnpj`, `br_cpf`, `ca_bn`, `ca_qst`, `ch_vat`, `cl_tin`, `es_cif`, `eu_vat`, `hk_br`, `id_npwp`, `in_gst`, `jp_cn`, `jp_rn`, `kr_brn`, `li_uid`, `mx_rfc`, `my_frp`, `my_itn`, `my_sst`, `no_vat`, `nz_gst`, `ru_inn`, `ru_kpp`, `sa_vat`, `sg_gst`, `sg_uen`, `th_vat`, `tw_vat`, `us_ein`, or `za_vat`. Note that some legacy tax IDs have type `unknown` *)
    _type: Enums.invoices_resource_invoice_tax_id_type;
    (* Value of the tax ID. *)
    value: string;
    (* Tax ID verification information. *)
    verification: Any_oftax_id_verification.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** You can add one or multiple tax IDs to a [customer](https://stripe.com/docs/api/customers). A customer's tax IDs are displayed on invoices and credit notes issued for the customer.  Related guide: [Customer Tax Identification Numbers](https://stripe.com/docs/billing/taxes/tax-ids). *)
let create (created : int32) (id : string) (livemode : bool) (_object : Enums.deleted_tax_id_object) (_type : Enums.invoices_resource_invoice_tax_id_type) (value : string) : t = {
    country = None;
    created = created;
    customer = None;
    id = id;
    livemode = livemode;
    _object = _object;
    _type = _type;
    value = value;
    verification = None;
}

