(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = { html : string; self : string }
[@@deriving yojson { strict = false }, show]

let create (html : string) (self : string) : t = { html; self }
