(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Commit_activity.t : Commit Activity
 *)

type t = { days : int32 list; total : int32; week : int32 }
[@@deriving yojson { strict = false }, show]

(** Commit Activity *)
let create (days : int32 list) (total : int32) (week : int32) : t =
  { days; total; week }
