(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Billing email address. This address is not publicized. *)
  billing_email : string option; [@default None]
  (* The company name. *)
  company : string option; [@default None]
  (* The publicly visible email address. *)
  email : string option; [@default None]
  (* The Twitter username of the company. *)
  twitter_username : string option; [@default None]
  (* The location. *)
  location : string option; [@default None]
  (* The shorthand name of the company. *)
  name : string option; [@default None]
  (* The description of the company. *)
  description : string option; [@default None]
  (* Toggles whether an organization can use organization projects. *)
  has_organization_projects : bool option; [@default None]
  (* Toggles whether repositories that belong to the organization can use repository projects. *)
  has_repository_projects : bool option; [@default None]
  (* Default permission level members have for organization repositories:   \\* `read` - can pull, but not push to or administer this repository.   \\* `write` - can pull and push, but not administer this repository.   \\* `admin` - can pull, push, and administer this repository.   \\* `none` - no permissions granted by default. *)
  default_repository_permission : Enums.organization_permission option;
      [@default Some `Read]
  (* Toggles the ability of non-admin organization members to create repositories. Can be one of:   \\* `true` - all organization members can create repositories.   \\* `false` - only organization owners can create repositories.   Default: `true`   **Note:** A parameter can override this parameter. See `members_allowed_repository_creation_type` in this table for details. **Note:** A parameter can override this parameter. See `members_allowed_repository_creation_type` in this table for details. *)
  members_can_create_repositories : bool option; [@default None]
  (* Toggles whether organization members can create internal repositories, which are visible to all enterprise members. You can only allow members to create internal repositories if your organization is associated with an enterprise account using GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+. Can be one of:   \\* `true` - all organization members can create internal repositories.   \\* `false` - only organization owners can create internal repositories.   Default: `true`. For more information, see \''[Restricting repository creation in your organization](https://help.github.com/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization)\'' in the GitHub Help documentation. *)
  members_can_create_internal_repositories : bool option; [@default None]
  (* Toggles whether organization members can create private repositories, which are visible to organization members with permission. Can be one of:   \\* `true` - all organization members can create private repositories.   \\* `false` - only organization owners can create private repositories.   Default: `true`. For more information, see \''[Restricting repository creation in your organization](https://help.github.com/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization)\'' in the GitHub Help documentation. *)
  members_can_create_private_repositories : bool option; [@default None]
  (* Toggles whether organization members can create public repositories, which are visible to anyone. Can be one of:   \\* `true` - all organization members can create public repositories.   \\* `false` - only organization owners can create public repositories.   Default: `true`. For more information, see \''[Restricting repository creation in your organization](https://help.github.com/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization)\'' in the GitHub Help documentation. *)
  members_can_create_public_repositories : bool option; [@default None]
  (* Specifies which types of repositories non-admin organization members can create. Can be one of:   \\* `all` - all organization members can create public and private repositories.   \\* `private` - members can create private repositories. This option is only available to repositories that are part of an organization on GitHub Enterprise Cloud.   \\* `none` - only admin members can create repositories.   **Note:** This parameter is deprecated and will be removed in the future. Its return value ignores internal repositories. Using this parameter overrides values set in `members_can_create_repositories`. See the parameter deprecation notice in the operation description for details. *)
  members_allowed_repository_creation_type :
    Enums.members_allowed_repository_creation_type option;
      [@default None]
  (* Toggles whether organization members can create GitHub Pages sites. Can be one of:   \\* `true` - all organization members can create GitHub Pages sites.   \\* `false` - no organization members can create GitHub Pages sites. Existing published sites will not be impacted.   Default: `true`.  *)
  members_can_create_pages : bool option; [@default None]
  blog : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    billing_email = None;
    company = None;
    email = None;
    twitter_username = None;
    location = None;
    name = None;
    description = None;
    has_organization_projects = None;
    has_repository_projects = None;
    default_repository_permission = None;
    members_can_create_repositories = None;
    members_can_create_internal_repositories = None;
    members_can_create_private_repositories = None;
    members_can_create_public_repositories = None;
    members_allowed_repository_creation_type = None;
    members_can_create_pages = None;
    blog = None;
  }
