(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* A list of scopes that this authorization is in. *)
  scopes : string list;
  (* A list of scopes to add to this authorization. *)
  add_scopes : string list;
  (* A list of scopes to remove from this authorization. *)
  remove_scopes : string list;
  (* A note to remind you what the OAuth token is for. *)
  note : string option; [@default None]
  (* A URL to remind you what app the OAuth token is for. *)
  note_url : string option; [@default None]
  (* A unique string to distinguish an authorization from others created for the same client ID and user. *)
  fingerprint : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    scopes = [];
    add_scopes = [];
    remove_scopes = [];
    note = None;
    note_url = None;
    fingerprint = None;
  }
