(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  name : string;
  space : int32;
  private_repos : int32;
  filled_seats : int32 option; [@default None]
  seats : int32 option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create (name : string) (space : int32) (private_repos : int32) : t =
  { name; space; private_repos; filled_seats = None; seats = None }
