(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = { branch : string; path : string }
[@@deriving yojson { strict = false }, show]

let create (branch : string) (path : string) : t = { branch; path }
