(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Pull_request_review.t : Pull Request Reviews are reviews on pull requests.
 *)

type t = {
  (* Unique identifier of the review *)
  id : int32;
  node_id : string;
  user : Simple_user.t option;
  (* The text of the review. *)
  body : string;
  state : string;
  html_url : string;
  pull_request_url : string;
  _links : Pull_request_review__links.t;
  submitted_at : string option; [@default None]
  (* A commit SHA for the review. *)
  commit_id : string;
  body_html : string option; [@default None]
  body_text : string option; [@default None]
  author_association : string;
}
[@@deriving yojson { strict = false }, show]

(** Pull Request Reviews are reviews on pull requests. *)
let create (id : int32) (node_id : string) (user : Simple_user.t option)
    (body : string) (state : string) (html_url : string)
    (pull_request_url : string) (_links : Pull_request_review__links.t)
    (commit_id : string) (author_association : string) : t =
  {
    id;
    node_id;
    user;
    body;
    state;
    html_url;
    pull_request_url;
    _links;
    submitted_at = None;
    commit_id;
    body_html = None;
    body_text = None;
    author_association;
  }
