(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  id : int32 option; [@default None]
  node_id : string option; [@default None]
  name : string option; [@default None]
  full_name : string option; [@default None]
  owner : Repository_template_repository_owner.t option; [@default None]
  _private : bool option; [@default None]
  html_url : string option; [@default None]
  description : string option; [@default None]
  fork : bool option; [@default None]
  url : string option; [@default None]
  archive_url : string option; [@default None]
  assignees_url : string option; [@default None]
  blobs_url : string option; [@default None]
  branches_url : string option; [@default None]
  collaborators_url : string option; [@default None]
  comments_url : string option; [@default None]
  commits_url : string option; [@default None]
  compare_url : string option; [@default None]
  contents_url : string option; [@default None]
  contributors_url : string option; [@default None]
  deployments_url : string option; [@default None]
  downloads_url : string option; [@default None]
  events_url : string option; [@default None]
  forks_url : string option; [@default None]
  git_commits_url : string option; [@default None]
  git_refs_url : string option; [@default None]
  git_tags_url : string option; [@default None]
  git_url : string option; [@default None]
  issue_comment_url : string option; [@default None]
  issue_events_url : string option; [@default None]
  issues_url : string option; [@default None]
  keys_url : string option; [@default None]
  labels_url : string option; [@default None]
  languages_url : string option; [@default None]
  merges_url : string option; [@default None]
  milestones_url : string option; [@default None]
  notifications_url : string option; [@default None]
  pulls_url : string option; [@default None]
  releases_url : string option; [@default None]
  ssh_url : string option; [@default None]
  stargazers_url : string option; [@default None]
  statuses_url : string option; [@default None]
  subscribers_url : string option; [@default None]
  subscription_url : string option; [@default None]
  tags_url : string option; [@default None]
  teams_url : string option; [@default None]
  trees_url : string option; [@default None]
  clone_url : string option; [@default None]
  mirror_url : string option; [@default None]
  hooks_url : string option; [@default None]
  svn_url : string option; [@default None]
  homepage : string option; [@default None]
  language : string option; [@default None]
  forks_count : int32 option; [@default None]
  stargazers_count : int32 option; [@default None]
  watchers_count : int32 option; [@default None]
  size : int32 option; [@default None]
  default_branch : string option; [@default None]
  open_issues_count : int32 option; [@default None]
  is_template : bool option; [@default None]
  topics : string list;
  has_issues : bool option; [@default None]
  has_projects : bool option; [@default None]
  has_wiki : bool option; [@default None]
  has_pages : bool option; [@default None]
  has_downloads : bool option; [@default None]
  archived : bool option; [@default None]
  disabled : bool option; [@default None]
  visibility : string option; [@default None]
  pushed_at : string option; [@default None]
  created_at : string option; [@default None]
  updated_at : string option; [@default None]
  permissions : Repository_template_repository_permissions.t option;
      [@default None]
  allow_rebase_merge : bool option; [@default None]
  template_repository : string option; [@default None]
  temp_clone_token : string option; [@default None]
  allow_squash_merge : bool option; [@default None]
  delete_branch_on_merge : bool option; [@default None]
  allow_merge_commit : bool option; [@default None]
  subscribers_count : int32 option; [@default None]
  network_count : int32 option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    id = None;
    node_id = None;
    name = None;
    full_name = None;
    owner = None;
    _private = None;
    html_url = None;
    description = None;
    fork = None;
    url = None;
    archive_url = None;
    assignees_url = None;
    blobs_url = None;
    branches_url = None;
    collaborators_url = None;
    comments_url = None;
    commits_url = None;
    compare_url = None;
    contents_url = None;
    contributors_url = None;
    deployments_url = None;
    downloads_url = None;
    events_url = None;
    forks_url = None;
    git_commits_url = None;
    git_refs_url = None;
    git_tags_url = None;
    git_url = None;
    issue_comment_url = None;
    issue_events_url = None;
    issues_url = None;
    keys_url = None;
    labels_url = None;
    languages_url = None;
    merges_url = None;
    milestones_url = None;
    notifications_url = None;
    pulls_url = None;
    releases_url = None;
    ssh_url = None;
    stargazers_url = None;
    statuses_url = None;
    subscribers_url = None;
    subscription_url = None;
    tags_url = None;
    teams_url = None;
    trees_url = None;
    clone_url = None;
    mirror_url = None;
    hooks_url = None;
    svn_url = None;
    homepage = None;
    language = None;
    forks_count = None;
    stargazers_count = None;
    watchers_count = None;
    size = None;
    default_branch = None;
    open_issues_count = None;
    is_template = None;
    topics = [];
    has_issues = None;
    has_projects = None;
    has_wiki = None;
    has_pages = None;
    has_downloads = None;
    archived = None;
    disabled = None;
    visibility = None;
    pushed_at = None;
    created_at = None;
    updated_at = None;
    permissions = None;
    allow_rebase_merge = None;
    template_repository = None;
    temp_clone_token = None;
    allow_squash_merge = None;
    delete_branch_on_merge = None;
    allow_merge_commit = None;
    subscribers_count = None;
    network_count = None;
  }
