(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val code_scanning_get_alert : owner:string -> repo:string -> alert_number:int32 -> Code_scanning_alert_code_scanning_alert.t Lwt.t
val code_scanning_list_alerts_for_repo : owner:string -> repo:string -> ?state:Enums.code_scanning_alert_state -> ?ref:string -> unit -> Code_scanning_alert_code_scanning_alert_items.t list Lwt.t
val code_scanning_list_recent_analyses : owner:string -> repo:string -> ?ref:string -> ?tool_name:string -> unit -> Code_scanning_analysis_code_scanning_analysis.t list Lwt.t
val code_scanning_update_alert : owner:string -> repo:string -> alert_number:int32 -> inline_object_86_t:Inline_object_86.t -> unit -> Code_scanning_alert_code_scanning_alert.t Lwt.t
val code_scanning_upload_sarif : owner:string -> repo:string -> inline_object_87_t:Inline_object_87.t -> unit -> unit Lwt.t
