(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val enterprise_admin_add_authorized_ssh_key : inline_object_152_t:Inline_object_152.t -> unit -> Ssh_key.t list Lwt.t
val enterprise_admin_add_org_access_to_self_hosted_runner_group_in_enterprise : enterprise:string -> runner_group_id:int32 -> org_id:int32 -> unit Lwt.t
val enterprise_admin_add_self_hosted_runner_to_group_for_enterprise : enterprise:string -> runner_group_id:int32 -> runner_id:int32 -> unit Lwt.t
val enterprise_admin_create_enterprise_server_license : inline_object_154_t:Inline_object_154.t -> unit -> unit Lwt.t
val enterprise_admin_create_global_webhook : accept:string -> inline_object_t:Inline_object.t -> unit -> Global_hook.t Lwt.t
val enterprise_admin_create_impersonation_o_auth_token : username:string -> inline_object_12_t:Inline_object_12.t -> unit -> Authorization.t Lwt.t
val enterprise_admin_create_org : inline_object_4_t:Inline_object_4.t -> unit -> Organization_simple.t Lwt.t
val enterprise_admin_create_pre_receive_environment : inline_object_6_t:Inline_object_6.t -> unit -> Pre_receive_environment.t Lwt.t
val enterprise_admin_create_pre_receive_hook : inline_object_8_t:Inline_object_8.t -> unit -> Pre_receive_hook.t Lwt.t
val enterprise_admin_create_registration_token_for_enterprise : enterprise:string -> Authentication_token.t Lwt.t
val enterprise_admin_create_remove_token_for_enterprise : enterprise:string -> Authentication_token.t Lwt.t
val enterprise_admin_create_self_hosted_runner_group_for_enterprise : enterprise:string -> inline_object_23_t:Inline_object_23.t -> unit -> Runner_groups_enterprise.t Lwt.t
val enterprise_admin_create_user : inline_object_10_t:Inline_object_10.t -> unit -> Simple_user.t Lwt.t
val enterprise_admin_delete_global_webhook : accept:string -> hook_id:int32 -> unit Lwt.t
val enterprise_admin_delete_impersonation_o_auth_token : username:string -> unit Lwt.t
val enterprise_admin_delete_personal_access_token : token_id:int32 -> unit Lwt.t
val enterprise_admin_delete_pre_receive_environment : pre_receive_environment_id:int32 -> unit Lwt.t
val enterprise_admin_delete_pre_receive_hook : pre_receive_hook_id:int32 -> unit Lwt.t
val enterprise_admin_delete_public_key : key_ids:string -> unit Lwt.t
val enterprise_admin_delete_self_hosted_runner_from_enterprise : enterprise:string -> runner_id:int32 -> unit Lwt.t
val enterprise_admin_delete_self_hosted_runner_group_from_enterprise : enterprise:string -> runner_group_id:int32 -> unit Lwt.t
val enterprise_admin_delete_user : username:string -> unit Lwt.t
val enterprise_admin_demote_site_administrator : username:string -> unit Lwt.t
val enterprise_admin_enable_or_disable_maintenance_mode : inline_object_150_t:Inline_object_150.t -> unit -> Maintenance_status.t Lwt.t
val enterprise_admin_get_all_authorized_ssh_keys : unit -> Ssh_key.t list Lwt.t
val enterprise_admin_get_configuration_status : unit -> Configuration_status.t Lwt.t
val enterprise_admin_get_download_status_for_pre_receive_environment : pre_receive_environment_id:int32 -> Pre_receive_environment_download_status.t Lwt.t
val enterprise_admin_get_global_webhook : accept:string -> hook_id:int32 -> Global_hook.t Lwt.t
val enterprise_admin_get_license_information : unit -> License_info.t Lwt.t
val enterprise_admin_get_maintenance_status : unit -> Maintenance_status.t Lwt.t
val enterprise_admin_get_pre_receive_environment : pre_receive_environment_id:int32 -> Pre_receive_environment.t Lwt.t
val enterprise_admin_get_pre_receive_hook : pre_receive_hook_id:int32 -> Pre_receive_hook.t Lwt.t
val enterprise_admin_get_pre_receive_hook_for_org : org:string -> pre_receive_hook_id:int32 -> Org_pre_receive_hook.t Lwt.t
val enterprise_admin_get_pre_receive_hook_for_repo : owner:string -> repo:string -> pre_receive_hook_id:int32 -> Repository_pre_receive_hook.t Lwt.t
val enterprise_admin_get_self_hosted_runner_for_enterprise : enterprise:string -> runner_id:int32 -> Runner_no_labels.t Lwt.t
val enterprise_admin_get_self_hosted_runner_group_for_enterprise : enterprise:string -> runner_group_id:int32 -> Runner_groups_enterprise.t Lwt.t
val enterprise_admin_get_settings : unit -> Enterprise_settings.t Lwt.t
val enterprise_admin_get_type_stats : _type:string -> Enterprise_overview.t Lwt.t
val enterprise_admin_list_global_webhooks : accept:string -> ?per_page:int32 -> ?page:int32 -> unit -> Global_hook.t list Lwt.t
val enterprise_admin_list_org_access_to_self_hosted_runner_group_in_enterprise : enterprise:string -> runner_group_id:int32 -> ?per_page:int32 -> ?page:int32 -> unit -> Inline_response_200_2.t Lwt.t
val enterprise_admin_list_personal_access_tokens : ?per_page:int32 -> ?page:int32 -> unit -> Authorization.t list Lwt.t
val enterprise_admin_list_pre_receive_environments : ?per_page:int32 -> ?page:int32 -> unit -> Pre_receive_environment.t list Lwt.t
val enterprise_admin_list_pre_receive_hooks : ?per_page:int32 -> ?page:int32 -> unit -> Pre_receive_hook.t list Lwt.t
val enterprise_admin_list_pre_receive_hooks_for_org : org:string -> ?per_page:int32 -> ?page:int32 -> unit -> Org_pre_receive_hook.t list Lwt.t
val enterprise_admin_list_pre_receive_hooks_for_repo : owner:string -> repo:string -> ?per_page:int32 -> ?page:int32 -> unit -> Repository_pre_receive_hook.t list Lwt.t
val enterprise_admin_list_public_keys : ?per_page:int32 -> ?page:int32 -> unit -> Enterprise_public_key.t list Lwt.t
val enterprise_admin_list_runner_applications_for_enterprise : enterprise:string -> Runner_application.t list Lwt.t
val enterprise_admin_list_self_hosted_runner_groups_for_enterprise : enterprise:string -> ?per_page:int32 -> ?page:int32 -> unit -> Inline_response_200_1.t Lwt.t
val enterprise_admin_list_self_hosted_runners_for_enterprise : enterprise:string -> ?per_page:int32 -> ?page:int32 -> unit -> Inline_response_200_3.t Lwt.t
val enterprise_admin_list_self_hosted_runners_in_group_for_enterprise : enterprise:string -> runner_group_id:int32 -> ?per_page:int32 -> ?page:int32 -> unit -> Inline_response_200_3.t Lwt.t
val enterprise_admin_ping_global_webhook : accept:string -> hook_id:int32 -> unit Lwt.t
val enterprise_admin_promote_user_to_be_site_administrator : username:string -> unit Lwt.t
val enterprise_admin_remove_authorized_ssh_key : inline_object_153_t:Inline_object_153.t -> unit -> Ssh_key.t list Lwt.t
val enterprise_admin_remove_org_access_to_self_hosted_runner_group_in_enterprise : enterprise:string -> runner_group_id:int32 -> org_id:int32 -> unit Lwt.t
val enterprise_admin_remove_pre_receive_hook_enforcement_for_org : org:string -> pre_receive_hook_id:int32 -> Org_pre_receive_hook.t Lwt.t
val enterprise_admin_remove_pre_receive_hook_enforcement_for_repo : owner:string -> repo:string -> pre_receive_hook_id:int32 -> Repository_pre_receive_hook.t Lwt.t
val enterprise_admin_remove_self_hosted_runner_from_group_for_enterprise : enterprise:string -> runner_group_id:int32 -> runner_id:int32 -> unit Lwt.t
val enterprise_admin_set_org_access_to_self_hosted_runner_group_in_enterprise : enterprise:string -> runner_group_id:int32 -> inline_object_25_t:Inline_object_25.t -> unit -> unit Lwt.t
val enterprise_admin_set_self_hosted_runners_in_group_for_enterprise : enterprise:string -> runner_group_id:int32 -> inline_object_26_t:Inline_object_26.t -> unit -> unit Lwt.t
val enterprise_admin_set_settings : inline_object_151_t:Inline_object_151.t -> unit -> unit Lwt.t
val enterprise_admin_start_configuration_process : unit -> unit Lwt.t
val enterprise_admin_start_pre_receive_environment_download : pre_receive_environment_id:int32 -> Pre_receive_environment_download_status.t Lwt.t
val enterprise_admin_suspend_user : username:string -> inline_object_172_t:Inline_object_172.t -> unit -> unit Lwt.t
val enterprise_admin_sync_ldap_mapping_for_team : team_id:int32 -> Inline_response_201.t Lwt.t
val enterprise_admin_sync_ldap_mapping_for_user : username:string -> Inline_response_201.t Lwt.t
val enterprise_admin_unsuspend_user : username:string -> inline_object_173_t:Inline_object_173.t -> unit -> unit Lwt.t
val enterprise_admin_update_global_webhook : accept:string -> hook_id:int32 -> inline_object_1_t:Inline_object_1.t -> unit -> Global_hook_2.t Lwt.t
val enterprise_admin_update_ldap_mapping_for_team : team_id:int32 -> inline_object_2_t:Inline_object_2.t -> unit -> Ldap_mapping_team.t Lwt.t
val enterprise_admin_update_ldap_mapping_for_user : username:string -> inline_object_3_t:Inline_object_3.t -> unit -> Ldap_mapping_user.t Lwt.t
val enterprise_admin_update_org_name : org:string -> inline_object_5_t:Inline_object_5.t -> unit -> Inline_response_202.t Lwt.t
val enterprise_admin_update_pre_receive_environment : pre_receive_environment_id:int32 -> inline_object_7_t:Inline_object_7.t -> unit -> Pre_receive_environment.t Lwt.t
val enterprise_admin_update_pre_receive_hook : pre_receive_hook_id:int32 -> inline_object_9_t:Inline_object_9.t -> unit -> Pre_receive_hook.t Lwt.t
val enterprise_admin_update_pre_receive_hook_enforcement_for_org : org:string -> pre_receive_hook_id:int32 -> inline_object_43_t:Inline_object_43.t -> unit -> Org_pre_receive_hook.t Lwt.t
val enterprise_admin_update_pre_receive_hook_enforcement_for_repo : owner:string -> repo:string -> pre_receive_hook_id:int32 -> inline_object_126_t:Inline_object_126.t -> unit -> Repository_pre_receive_hook.t Lwt.t
val enterprise_admin_update_self_hosted_runner_group_for_enterprise : enterprise:string -> runner_group_id:int32 -> inline_object_24_t:Inline_object_24.t -> unit -> Runner_groups_enterprise.t Lwt.t
val enterprise_admin_update_username_for_user : username:string -> inline_object_11_t:Inline_object_11.t -> unit -> Inline_response_202.t Lwt.t
val enterprise_admin_upgrade_license : inline_object_155_t:Inline_object_155.t -> unit -> unit Lwt.t
