(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val gists_check_is_starred : gist_id:string -> unit Lwt.t
val gists_create : inline_object_27_t:Inline_object_27.t -> unit -> Gist_full.t Lwt.t
val gists_create_comment : gist_id:string -> inline_object_28_t:Inline_object_28.t -> unit -> Gist_comment.t Lwt.t
val gists_delete : gist_id:string -> unit Lwt.t
val gists_delete_comment : gist_id:string -> comment_id:int32 -> unit Lwt.t
val gists_fork : gist_id:string -> Base_gist.t Lwt.t
val gists_get : gist_id:string -> Gist_full.t Lwt.t
val gists_get_comment : gist_id:string -> comment_id:int32 -> Gist_comment.t Lwt.t
val gists_get_revision : gist_id:string -> sha:string -> Gist_full.t Lwt.t
val gists_list : ?since:string -> ?per_page:int32 -> ?page:int32 -> unit -> Base_gist.t list Lwt.t
val gists_list_comments : gist_id:string -> ?per_page:int32 -> ?page:int32 -> unit -> Gist_comment.t list Lwt.t
val gists_list_commits : gist_id:string -> ?per_page:int32 -> ?page:int32 -> unit -> Gist_commit.t list Lwt.t
val gists_list_for_user : username:string -> ?since:string -> ?per_page:int32 -> ?page:int32 -> unit -> Base_gist.t list Lwt.t
val gists_list_forks : gist_id:string -> ?per_page:int32 -> ?page:int32 -> unit -> Gist_full.t list Lwt.t
val gists_list_public : ?since:string -> ?per_page:int32 -> ?page:int32 -> unit -> Base_gist.t list Lwt.t
val gists_list_starred : ?since:string -> ?per_page:int32 -> ?page:int32 -> unit -> Base_gist.t list Lwt.t
val gists_star : gist_id:string -> unit Lwt.t
val gists_unstar : gist_id:string -> unit Lwt.t
val gists_update : gist_id:string -> unknown_base_type -> unit -> Gist_full.t Lwt.t
val gists_update_comment : gist_id:string -> comment_id:int32 -> inline_object_29_t:Inline_object_29.t -> unit -> Gist_comment.t Lwt.t
