(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val projects_add_collaborator : project_id:int32 -> username:string -> inline_object_62_t:Inline_object_62.t -> unit -> unit Lwt.t
val projects_create_card : column_id:int32 -> unknown_base_type:UNKNOWN_BASE_TYPE -> unit -> Project_card.t Lwt.t
val projects_create_column : project_id:int32 -> inline_object_63_t:Inline_object_63.t -> unit -> Project_column.t Lwt.t
val projects_create_for_authenticated_user : inline_object_170_t:Inline_object_170.t -> unit -> Project.t Lwt.t
val projects_create_for_org : org:string -> inline_object_44_t:Inline_object_44.t -> unit -> Project.t Lwt.t
val projects_create_for_repo : owner:string -> repo:string -> inline_object_127_t:Inline_object_127.t -> unit -> Project.t Lwt.t
val projects_delete : project_id:int32 -> unit Lwt.t
val projects_delete_card : card_id:int32 -> unit Lwt.t
val projects_delete_column : column_id:int32 -> unit Lwt.t
val projects_get : project_id:int32 -> Project.t Lwt.t
val projects_get_card : card_id:int32 -> Project_card.t Lwt.t
val projects_get_column : column_id:int32 -> Project_column.t Lwt.t
val projects_get_permission_for_user : project_id:int32 -> username:string -> Repository_collaborator_permission.t Lwt.t
val projects_list_cards : column_id:int32 -> ?archived_state:Enums.archived_state -> ?per_page:int32 -> ?page:int32 -> unit -> Project_card.t list Lwt.t
val projects_list_collaborators : project_id:int32 -> ?affiliation:Enums.affiliation -> ?per_page:int32 -> ?page:int32 -> unit -> Simple_user.t list Lwt.t
val projects_list_columns : project_id:int32 -> ?per_page:int32 -> ?page:int32 -> unit -> Project_column.t list Lwt.t
val projects_list_for_org : org:string -> ?state:Enums.state_1 -> ?per_page:int32 -> ?page:int32 -> unit -> Project.t list Lwt.t
val projects_list_for_repo : owner:string -> repo:string -> ?state:Enums.state_1 -> ?per_page:int32 -> ?page:int32 -> unit -> Project.t list Lwt.t
val projects_list_for_user : username:string -> ?state:Enums.state_1 -> ?per_page:int32 -> ?page:int32 -> unit -> Project.t list Lwt.t
val projects_move_card : card_id:int32 -> inline_object_58_t:Inline_object_58.t -> unit -> Yojson.Safe.t Lwt.t
val projects_move_column : column_id:int32 -> inline_object_60_t:Inline_object_60.t -> unit -> Yojson.Safe.t Lwt.t
val projects_remove_collaborator : project_id:int32 -> username:string -> unit Lwt.t
val projects_update : project_id:int32 -> inline_object_61_t:Inline_object_61.t -> unit -> Project.t Lwt.t
val projects_update_card : card_id:int32 -> inline_object_57_t:Inline_object_57.t -> unit -> Project_card.t Lwt.t
val projects_update_column : column_id:int32 -> inline_object_59_t:Inline_object_59.t -> unit -> Project_column.t Lwt.t
