(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val pulls_check_if_merged : owner:string -> repo:string -> pull_number:int32 -> unit Lwt.t
val pulls_create : owner:string -> repo:string -> inline_object_128_t:Inline_object_128.t -> unit -> Pull_request.t Lwt.t
val pulls_create_reply_for_review_comment : owner:string -> repo:string -> pull_number:int32 -> comment_id:int32 -> inline_object_133_t:Inline_object_133.t -> unit -> Pull_request_review_comment.t Lwt.t
val pulls_create_review : owner:string -> repo:string -> pull_number:int32 -> inline_object_137_t:Inline_object_137.t -> unit -> Pull_request_review.t Lwt.t
val pulls_create_review_comment : owner:string -> repo:string -> pull_number:int32 -> inline_object_132_t:Inline_object_132.t -> unit -> Pull_request_review_comment.t Lwt.t
val pulls_delete_pending_review : owner:string -> repo:string -> pull_number:int32 -> review_id:int32 -> Pull_request_review.t Lwt.t
val pulls_delete_review_comment : owner:string -> repo:string -> comment_id:int32 -> unit Lwt.t
val pulls_dismiss_review : owner:string -> repo:string -> pull_number:int32 -> review_id:int32 -> inline_object_139_t:Inline_object_139.t -> unit -> Pull_request_review.t Lwt.t
val pulls_get : owner:string -> repo:string -> pull_number:int32 -> Pull_request.t Lwt.t
val pulls_get_review : owner:string -> repo:string -> pull_number:int32 -> review_id:int32 -> Pull_request_review.t Lwt.t
val pulls_get_review_comment : owner:string -> repo:string -> comment_id:int32 -> Pull_request_review_comment.t Lwt.t
val pulls_list : owner:string -> repo:string -> ?state:Enums.state_1 -> ?head:string -> ?base:string -> ?sort:Enums.sort_1 -> ?direction:Enums.direction -> ?per_page:int32 -> ?page:int32 -> unit -> Pull_request_simple.t list Lwt.t
val pulls_list_comments_for_review : owner:string -> repo:string -> pull_number:int32 -> review_id:int32 -> ?per_page:int32 -> ?page:int32 -> unit -> Review_comment.t list Lwt.t
val pulls_list_commits : owner:string -> repo:string -> pull_number:int32 -> ?per_page:int32 -> ?page:int32 -> unit -> Commit.t list Lwt.t
val pulls_list_files : owner:string -> repo:string -> pull_number:int32 -> ?per_page:int32 -> ?page:int32 -> unit -> Diff_entry.t list Lwt.t
val pulls_list_requested_reviewers : owner:string -> repo:string -> pull_number:int32 -> ?per_page:int32 -> ?page:int32 -> unit -> Pull_request_review_request.t Lwt.t
val pulls_list_review_comments : owner:string -> repo:string -> pull_number:int32 -> ?sort:Enums.sort_7 -> ?direction:Enums.direction -> ?since:string -> ?per_page:int32 -> ?page:int32 -> unit -> Pull_request_review_comment.t list Lwt.t
val pulls_list_review_comments_for_repo : owner:string -> repo:string -> ?sort:Enums.sort_7 -> ?direction:Enums.direction -> ?since:string -> ?per_page:int32 -> ?page:int32 -> unit -> Pull_request_review_comment.t list Lwt.t
val pulls_list_reviews : owner:string -> repo:string -> pull_number:int32 -> ?per_page:int32 -> ?page:int32 -> unit -> Pull_request_review.t list Lwt.t
val pulls_merge : owner:string -> repo:string -> pull_number:int32 -> inline_object_134_t:Inline_object_134.t -> unit -> Pull_request_merge_result.t Lwt.t
val pulls_remove_requested_reviewers : owner:string -> repo:string -> pull_number:int32 -> inline_object_136_t:Inline_object_136.t -> unit -> unit Lwt.t
val pulls_request_reviewers : owner:string -> repo:string -> pull_number:int32 -> inline_object_135_t:Inline_object_135.t -> unit -> Pull_request_simple.t Lwt.t
val pulls_submit_review : owner:string -> repo:string -> pull_number:int32 -> review_id:int32 -> inline_object_140_t:Inline_object_140.t -> unit -> Pull_request_review.t Lwt.t
val pulls_update : owner:string -> repo:string -> pull_number:int32 -> inline_object_131_t:Inline_object_131.t -> unit -> Pull_request.t Lwt.t
val pulls_update_branch : owner:string -> repo:string -> pull_number:int32 -> inline_object_141_t:Inline_object_141.t -> unit -> Inline_response_202.t Lwt.t
val pulls_update_review : owner:string -> repo:string -> pull_number:int32 -> review_id:int32 -> inline_object_138_t:Inline_object_138.t -> unit -> Pull_request_review.t Lwt.t
val pulls_update_review_comment : owner:string -> repo:string -> comment_id:int32 -> inline_object_129_t:Inline_object_129.t -> unit -> Pull_request_review_comment.t Lwt.t
