(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val reactions_create_for_commit_comment : owner:string -> repo:string -> comment_id:int32 -> inline_object_90_t:Inline_object_90.t -> unit -> Reaction.t Lwt.t
val reactions_create_for_issue : owner:string -> repo:string -> issue_number:int32 -> inline_object_116_t:Inline_object_116.t -> unit -> Reaction.t Lwt.t
val reactions_create_for_issue_comment : owner:string -> repo:string -> comment_id:int32 -> inline_object_108_t:Inline_object_108.t -> unit -> Reaction.t Lwt.t
val reactions_create_for_pull_request_review_comment : owner:string -> repo:string -> comment_id:int32 -> inline_object_130_t:Inline_object_130.t -> unit -> Reaction.t Lwt.t
val reactions_create_for_team_discussion_comment_in_org : org:string -> team_slug:string -> discussion_number:int32 -> comment_number:int32 -> inline_object_52_t:Inline_object_52.t -> unit -> Reaction.t Lwt.t
val reactions_create_for_team_discussion_comment_legacy : team_id:int32 -> discussion_number:int32 -> comment_number:int32 -> inline_object_161_t:Inline_object_161.t -> unit -> Reaction.t Lwt.t
val reactions_create_for_team_discussion_in_org : org:string -> team_slug:string -> discussion_number:int32 -> inline_object_53_t:Inline_object_53.t -> unit -> Reaction.t Lwt.t
val reactions_create_for_team_discussion_legacy : team_id:int32 -> discussion_number:int32 -> inline_object_162_t:Inline_object_162.t -> unit -> Reaction.t Lwt.t
val reactions_delete_for_commit_comment : owner:string -> repo:string -> comment_id:int32 -> reaction_id:int32 -> unit Lwt.t
val reactions_delete_for_issue : owner:string -> repo:string -> issue_number:int32 -> reaction_id:int32 -> unit Lwt.t
val reactions_delete_for_issue_comment : owner:string -> repo:string -> comment_id:int32 -> reaction_id:int32 -> unit Lwt.t
val reactions_delete_for_pull_request_comment : owner:string -> repo:string -> comment_id:int32 -> reaction_id:int32 -> unit Lwt.t
val reactions_delete_for_team_discussion : org:string -> team_slug:string -> discussion_number:int32 -> reaction_id:int32 -> unit Lwt.t
val reactions_delete_for_team_discussion_comment : org:string -> team_slug:string -> discussion_number:int32 -> comment_number:int32 -> reaction_id:int32 -> unit Lwt.t
val reactions_delete_legacy : reaction_id:int32 -> unit Lwt.t
val reactions_list_for_commit_comment : owner:string -> repo:string -> comment_id:int32 -> ?content:Enums.content -> ?per_page:int32 -> ?page:int32 -> unit -> Reaction.t list Lwt.t
val reactions_list_for_issue : owner:string -> repo:string -> issue_number:int32 -> ?content:Enums.content -> ?per_page:int32 -> ?page:int32 -> unit -> Reaction.t list Lwt.t
val reactions_list_for_issue_comment : owner:string -> repo:string -> comment_id:int32 -> ?content:Enums.content -> ?per_page:int32 -> ?page:int32 -> unit -> Reaction.t list Lwt.t
val reactions_list_for_pull_request_review_comment : owner:string -> repo:string -> comment_id:int32 -> ?content:Enums.content -> ?per_page:int32 -> ?page:int32 -> unit -> Reaction.t list Lwt.t
val reactions_list_for_team_discussion_comment_in_org : org:string -> team_slug:string -> discussion_number:int32 -> comment_number:int32 -> ?content:Enums.content -> ?per_page:int32 -> ?page:int32 -> unit -> Reaction.t list Lwt.t
val reactions_list_for_team_discussion_comment_legacy : team_id:int32 -> discussion_number:int32 -> comment_number:int32 -> ?content:Enums.content -> ?per_page:int32 -> ?page:int32 -> unit -> Reaction.t list Lwt.t
val reactions_list_for_team_discussion_in_org : org:string -> team_slug:string -> discussion_number:int32 -> ?content:Enums.content -> ?per_page:int32 -> ?page:int32 -> unit -> Reaction.t list Lwt.t
val reactions_list_for_team_discussion_legacy : team_id:int32 -> discussion_number:int32 -> ?content:Enums.content -> ?per_page:int32 -> ?page:int32 -> unit -> Reaction.t list Lwt.t
