(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Api_overview.t : Api Overview
 *)

type t = {
    verifiable_password_authentication: bool;
    ssh_key_fingerprints: Api_overview_ssh_key_fingerprints.t option [@default None];
    hooks: string list;
    web: string list;
    api: string list;
    git: string list;
    pages: string list;
    importer: string list;
    github_services_sha: string option [@default None];
    installed_version: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Api Overview *)
let create (verifiable_password_authentication : bool) : t = {
    verifiable_password_authentication = verifiable_password_authentication;
    ssh_key_fingerprints = None;
    hooks = [];
    web = [];
    api = [];
    git = [];
    pages = [];
    importer = [];
    github_services_sha = None;
    installed_version = None;
}

