(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Branch_short.t : Branch Short
 *)

type t = {
    name: string option [@default None];
    commit: Branch_short_commit.t option [@default None];
    protected: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Branch Short *)
let create () : t = {
    name = None;
    commit = None;
    protected = None;
}

