(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    w: string option [@default None];
    a: int32 option [@default None];
    d: int32 option [@default None];
    c: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    w = None;
    a = None;
    d = None;
    c = None;
}

