(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    email: string;
    primary: bool;
    verified: bool;
    visibility: string option;
} [@@deriving yojson { strict = false }, show ];;

let create (email : string) (primary : bool) (verified : bool) (visibility : string option) : t = {
    email = email;
    primary = primary;
    verified = verified;
    visibility = visibility;
}

