(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string option [@default None];
    key_id: string option [@default None];
    key: string option [@default None];
    user_id: int32 option [@default None];
    repository_id: int32 option [@default None];
    url: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    id = None;
    key_id = None;
    key = None;
    user_id = None;
    repository_id = None;
    url = None;
}

