(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    name: string option [@default None];
    email: string option [@default None];
    uuid: string option [@default None];
    secret_key_data: string option [@default None];
    public_key_data: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    name = None;
    email = None;
    uuid = None;
    secret_key_data = None;
    public_key_data = None;
}

