(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    total_orgs: int32 option [@default None];
    disabled_orgs: int32 option [@default None];
    total_teams: int32 option [@default None];
    total_team_members: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    total_orgs = None;
    disabled_orgs = None;
    total_teams = None;
    total_team_members = None;
}

