(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    enabled: bool option [@default None];
    cert: string option [@default None];
    key: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    enabled = None;
    cert = None;
    key = None;
}

