(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    total_users: int32 option [@default None];
    admin_users: int32 option [@default None];
    suspended_users: int32 option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    total_users = None;
    admin_users = None;
    suspended_users = None;
}

