(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    client_id: string option [@default None];
    client_secret: string option [@default None];
    organization_name: string option [@default None];
    organization_team: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    client_id = None;
    client_secret = None;
    organization_name = None;
    organization_team = None;
}

