(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    self: string option [@default None];
    git: string option [@default None];
    html: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    self = None;
    git = None;
    html = None;
}

