(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    url: string option [@default None];
    version: string option [@default None];
    user: Gist_full_all_of_user.t option [@default None];
    change_status: Gist_full_all_of_change_status.t option [@default None];
    committed_at: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    url = None;
    version = None;
    user = None;
    change_status = None;
    committed_at = None;
}

