(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    current_user_url: string;
    current_user_authorizations_html_url: string;
    authorizations_url: string;
    code_search_url: string;
    commit_search_url: string;
    emails_url: string;
    emojis_url: string;
    events_url: string;
    feeds_url: string;
    followers_url: string;
    following_url: string;
    gists_url: string;
    hub_url: string;
    issue_search_url: string;
    issues_url: string;
    keys_url: string;
    label_search_url: string;
    notifications_url: string;
    organization_url: string;
    organization_repositories_url: string;
    organization_teams_url: string;
    public_gists_url: string;
    rate_limit_url: string;
    repository_url: string;
    repository_search_url: string;
    current_user_repositories_url: string;
    starred_url: string;
    starred_gists_url: string;
    topic_search_url: string option [@default None];
    user_url: string;
    user_organizations_url: string;
    user_repositories_url: string;
    user_search_url: string;
} [@@deriving yojson { strict = false }, show ];;

let create (current_user_url : string) (current_user_authorizations_html_url : string) (authorizations_url : string) (code_search_url : string) (commit_search_url : string) (emails_url : string) (emojis_url : string) (events_url : string) (feeds_url : string) (followers_url : string) (following_url : string) (gists_url : string) (hub_url : string) (issue_search_url : string) (issues_url : string) (keys_url : string) (label_search_url : string) (notifications_url : string) (organization_url : string) (organization_repositories_url : string) (organization_teams_url : string) (public_gists_url : string) (rate_limit_url : string) (repository_url : string) (repository_search_url : string) (current_user_repositories_url : string) (starred_url : string) (starred_gists_url : string) (user_url : string) (user_organizations_url : string) (user_repositories_url : string) (user_search_url : string) : t = {
    current_user_url = current_user_url;
    current_user_authorizations_html_url = current_user_authorizations_html_url;
    authorizations_url = authorizations_url;
    code_search_url = code_search_url;
    commit_search_url = commit_search_url;
    emails_url = emails_url;
    emojis_url = emojis_url;
    events_url = events_url;
    feeds_url = feeds_url;
    followers_url = followers_url;
    following_url = following_url;
    gists_url = gists_url;
    hub_url = hub_url;
    issue_search_url = issue_search_url;
    issues_url = issues_url;
    keys_url = keys_url;
    label_search_url = label_search_url;
    notifications_url = notifications_url;
    organization_url = organization_url;
    organization_repositories_url = organization_repositories_url;
    organization_teams_url = organization_teams_url;
    public_gists_url = public_gists_url;
    rate_limit_url = rate_limit_url;
    repository_url = repository_url;
    repository_search_url = repository_search_url;
    current_user_repositories_url = current_user_repositories_url;
    starred_url = starred_url;
    starred_gists_url = starred_gists_url;
    topic_search_url = None;
    user_url = user_url;
    user_organizations_url = user_organizations_url;
    user_repositories_url = user_repositories_url;
    user_search_url = user_search_url;
}

