(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    message: string option [@default None];
    documentation_url: string option [@default None];
    errors: Inline_response_403_3_errors.t list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    message = None;
    documentation_url = None;
    errors = [];
}

