(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Name of the project *)
    name: string option [@default None];
    (* Body of the project *)
    body: string option [@default None];
    (* State of the project; either 'open' or 'closed' *)
    state: string option [@default None];
    (* The baseline permission that all organization members have on this project *)
    organization_permission: Enums.organization_permission option [@default None];
    (* Whether or not this project can be seen by everyone. *)
    _private: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    name = None;
    body = None;
    state = None;
    organization_permission = None;
    _private = None;
}

