(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    reason: string option [@default None];
    created_at: string option [@default None];
    html_url: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    reason = None;
    created_at = None;
    html_url = None;
}

