(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The name of the project. *)
    name: string;
    (* The description of the project. *)
    body: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (name : string) : t = {
    name = name;
    body = None;
}

