(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The discussion post's title. *)
    title: string option [@default None];
    (* The discussion post's body text. *)
    body: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    title = None;
    body = None;
}

