(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The ref to deploy. This can be a branch, tag, or SHA. *)
    ref: string;
    (* Specifies a task to execute (e.g., `deploy` or `deploy:migrations`). *)
    task: string option [@default None];
    (* Attempts to automatically merge the default branch into the requested ref, if it's behind the default branch. *)
    auto_merge: bool option [@default None];
    (* The [status](https://docs.github.com/enterprise-server@2.22/rest/reference/repos#statuses) contexts to verify against commit status checks. If you omit this parameter, GitHub verifies all unique contexts before creating a deployment. To bypass checking entirely, pass an empty array. Defaults to all unique contexts. *)
    required_contexts: string list;
    (* JSON payload with extra information about the deployment. *)
    payload: string option [@default None];
    (* Name for the target deployment environment (e.g., `production`, `staging`, `qa`). *)
    environment: string option [@default None];
    (* Short description of the deployment. *)
    description: string option [@default None];
    (* Specifies if the given environment is specific to the deployment and will no longer exist at some point in the future. Default: `false`   **Note:** This parameter requires you to use the [`application/vnd.github.ant-man-preview+json`](https://docs.github.com/enterprise-server@2.22/rest/overview/api-previews#enhanced-deployments) custom media type. **Note:** This parameter requires you to use the [`application/vnd.github.ant-man-preview+json`](https://docs.github.com/enterprise-server@2.22/rest/overview/api-previews#enhanced-deployments) custom media type. *)
    transient_environment: bool option [@default None];
    (* Specifies if the given environment is one that end-users directly interact with. Default: `true` when `environment` is `production` and `false` otherwise.   **Note:** This parameter requires you to use the [`application/vnd.github.ant-man-preview+json`](https://docs.github.com/enterprise-server@2.22/rest/overview/api-previews#enhanced-deployments) custom media type. *)
    production_environment: bool option [@default None];
    created_at: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (ref : string) : t = {
    ref = ref;
    task = None;
    auto_merge = None;
    required_contexts = [];
    payload = None;
    environment = None;
    description = None;
    transient_environment = None;
    production_environment = None;
    created_at = None;
}

