(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The body text of the pull request review *)
    body: string option [@default None];
    (* The review action you want to perform. The review actions include: `APPROVE`, `REQUEST_CHANGES`, or `COMMENT`. When you leave this blank, the API returns _HTTP 422 (Unrecognizable entity)_ and sets the review action state to `PENDING`, which means you will need to re-submit the pull request review using a review action. *)
    event: Enums.event;
} [@@deriving yojson { strict = false }, show ];;

let create (event : Enums.event) : t = {
    body = None;
    event = event;
}

