(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The message for the pull request review dismissal *)
    message: string;
    event: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (message : string) : t = {
    message = message;
    event = None;
}

