(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The git reference for the workflow. The reference can be a branch or tag name. *)
    ref: string;
    (* Input keys and values configured in the workflow file. The maximum number of properties is 10. Any default properties configured in the workflow file will be used when `inputs` are omitted. *)
    inputs: (string * string) list;
} [@@deriving yojson { strict = false }, show ];;

let create (ref : string) : t = {
    ref = ref;
    inputs = [];
}

