(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Issue_event.t : Issue Event
 *)

type t = {
    id: int32;
    node_id: string;
    url: string;
    actor: Simple_user.t option;
    event: string;
    commit_id: string option;
    commit_url: string option;
    created_at: string;
    issue: Issue_simple.t option [@default None];
    label: Issue_event_label.t option [@default None];
    assignee: Simple_user.t option [@default None];
    assigner: Simple_user.t option [@default None];
    review_requester: Simple_user.t option [@default None];
    requested_reviewer: Simple_user.t option [@default None];
    requested_team: Team.t option [@default None];
    dismissed_review: Issue_event_dismissed_review.t option [@default None];
    milestone: Issue_event_milestone.t option [@default None];
    project_card: Issue_event_project_card.t option [@default None];
    rename: Issue_event_rename.t option [@default None];
    author_association: string option [@default None];
    lock_reason: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Issue Event *)
let create (id : int32) (node_id : string) (url : string) (actor : Simple_user.t option) (event : string) (commit_id : string option) (commit_url : string option) (created_at : string) : t = {
    id = id;
    node_id = node_id;
    url = url;
    actor = actor;
    event = event;
    commit_id = commit_id;
    commit_url = commit_url;
    created_at = created_at;
    issue = None;
    label = None;
    assignee = None;
    assigner = None;
    review_requester = None;
    requested_reviewer = None;
    requested_team = None;
    dismissed_review = None;
    milestone = None;
    project_card = None;
    rename = None;
    author_association = None;
    lock_reason = None;
}

