(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema License.t : License
 *)

type t = {
    key: string;
    name: string;
    spdx_id: string option;
    url: string option;
    node_id: string;
    html_url: string;
    description: string;
    implementation: string;
    permissions: string list;
    conditions: string list;
    limitations: string list;
    body: string;
    featured: bool;
} [@@deriving yojson { strict = false }, show ];;

(** License *)
let create (key : string) (name : string) (spdx_id : string option) (url : string option) (node_id : string) (html_url : string) (description : string) (implementation : string) (permissions : string list) (conditions : string list) (limitations : string list) (body : string) (featured : bool) : t = {
    key = key;
    name = name;
    spdx_id = spdx_id;
    url = url;
    node_id = node_id;
    html_url = html_url;
    description = description;
    implementation = implementation;
    permissions = permissions;
    conditions = conditions;
    limitations = limitations;
    body = body;
    featured = featured;
}

