(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema License_content.t : License Content
 *)

type t = {
    name: string;
    path: string;
    sha: string;
    size: int32;
    url: string;
    html_url: string option;
    git_url: string option;
    download_url: string option;
    _type: string;
    content: string;
    encoding: string;
    _links: Content_tree__links.t;
    license: License_simple.t option;
} [@@deriving yojson { strict = false }, show ];;

(** License Content *)
let create (name : string) (path : string) (sha : string) (size : int32) (url : string) (html_url : string option) (git_url : string option) (download_url : string option) (_type : string) (content : string) (encoding : string) (_links : Content_tree__links.t) (license : License_simple.t option) : t = {
    name = name;
    path = path;
    sha = sha;
    size = size;
    url = url;
    html_url = html_url;
    git_url = git_url;
    download_url = download_url;
    _type = _type;
    content = content;
    encoding = encoding;
    _links = _links;
    license = license;
}

