(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Milestone.t : A collection of related issues and pull requests.
 *)

type t = {
    url: string;
    html_url: string;
    labels_url: string;
    id: int32;
    node_id: string;
    (* The number of the milestone. *)
    number: int32;
    (* The state of the milestone. *)
    state: Enums.milestone_state[@default `_open];
    (* The title of the milestone. *)
    title: string;
    description: string option;
    creator: Simple_user.t option;
    open_issues: int32;
    closed_issues: int32;
    created_at: string;
    updated_at: string;
    closed_at: string option;
    due_on: string option;
} [@@deriving yojson { strict = false }, show ];;

(** A collection of related issues and pull requests. *)
let create (url : string) (html_url : string) (labels_url : string) (id : int32) (node_id : string) (number : int32) (state : Enums.milestone_state) (title : string) (description : string option) (creator : Simple_user.t option) (open_issues : int32) (closed_issues : int32) (created_at : string) (updated_at : string) (closed_at : string option) (due_on : string option) : t = {
    url = url;
    html_url = html_url;
    labels_url = labels_url;
    id = id;
    node_id = node_id;
    number = number;
    state = state;
    title = title;
    description = description;
    creator = creator;
    open_issues = open_issues;
    closed_issues = closed_issues;
    created_at = created_at;
    updated_at = updated_at;
    closed_at = closed_at;
    due_on = due_on;
}

