(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    contents: string option [@default None];
    issues: string option [@default None];
    deployments: string option [@default None];
    single_file: string option [@default None];
    def_not_a_repo: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    contents = None;
    issues = None;
    deployments = None;
    single_file = None;
    def_not_a_repo = None;
}

