(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Page.t : The configuration for GitHub Pages for a repository.
 *)

type t = {
    (* The API address for accessing this Page resource. *)
    url: string;
    (* The status of the most recent build of the Page. *)
    status: Enums.page_status option [@default None];
    (* The Pages site's custom domain *)
    cname: string option;
    (* Whether the Page has a custom 404 page. *)
    custom_404: bool;
    (* The web address the Page can be accessed from. *)
    html_url: string option [@default None];
    source: Pages_source_hash.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** The configuration for GitHub Pages for a repository. *)
let create (url : string) (status : Enums.page_status option) (cname : string option) (custom_404 : bool) : t = {
    url = url;
    status = status;
    cname = cname;
    custom_404 = custom_404;
    html_url = None;
    source = None;
}

