(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Pull_request_review_comment.t : Pull Request Review Comments are comments on a portion of the Pull Request's diff.
 *)

type t = {
    (* URL for the pull request review comment *)
    url: string;
    (* The ID of the pull request review to which the comment belongs. *)
    pull_request_review_id: int32 option;
    (* The ID of the pull request review comment. *)
    id: int32;
    (* The node ID of the pull request review comment. *)
    node_id: string;
    (* The diff of the line that the comment refers to. *)
    diff_hunk: string;
    (* The relative path of the file to which the comment applies. *)
    path: string;
    (* The line index in the diff to which the comment applies. *)
    position: int32;
    (* The index of the original line in the diff to which the comment applies. *)
    original_position: int32;
    (* The SHA of the commit to which the comment applies. *)
    commit_id: string;
    (* The SHA of the original commit to which the comment applies. *)
    original_commit_id: string;
    (* The comment ID to reply to. *)
    in_reply_to_id: int32 option [@default None];
    user: Simple_user.t option;
    (* The text of the comment. *)
    body: string;
    created_at: string;
    updated_at: string;
    (* HTML URL for the pull request review comment. *)
    html_url: string;
    (* URL for the pull request that the review comment belongs to. *)
    pull_request_url: string;
    (* How the author of the comment is associated with the pull request. *)
    author_association: string;
    _links: Pull_request_review_comment__links.t;
    (* The first line of the range for a multi-line comment. *)
    start_line: int32 option [@default None];
    (* The first line of the range for a multi-line comment. *)
    original_start_line: int32 option [@default None];
    (* The side of the first line of the range for a multi-line comment. *)
    start_side: Enums.start_side option [@default Some(`RIGHT)];
    (* The line of the blob to which the comment applies. The last line of the range for a multi-line comment *)
    line: int32 option [@default None];
    (* The line of the blob to which the comment applies. The last line of the range for a multi-line comment *)
    original_line: int32 option [@default None];
    (* The side of the diff to which the comment applies. The side of the last line of the range for a multi-line comment *)
    side: Enums.start_side option [@default Some(`RIGHT)];
    reactions: Reaction_rollup.t option [@default None];
    body_html: string option [@default None];
    body_text: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Pull Request Review Comments are comments on a portion of the Pull Request's diff. *)
let create (url : string) (pull_request_review_id : int32 option) (id : int32) (node_id : string) (diff_hunk : string) (path : string) (position : int32) (original_position : int32) (commit_id : string) (original_commit_id : string) (user : Simple_user.t option) (body : string) (created_at : string) (updated_at : string) (html_url : string) (pull_request_url : string) (author_association : string) (_links : Pull_request_review_comment__links.t) : t = {
    url = url;
    pull_request_review_id = pull_request_review_id;
    id = id;
    node_id = node_id;
    diff_hunk = diff_hunk;
    path = path;
    position = position;
    original_position = original_position;
    commit_id = commit_id;
    original_commit_id = original_commit_id;
    in_reply_to_id = None;
    user = user;
    body = body;
    created_at = created_at;
    updated_at = updated_at;
    html_url = html_url;
    pull_request_url = pull_request_url;
    author_association = author_association;
    _links = _links;
    start_line = None;
    original_start_line = None;
    start_side = None;
    line = None;
    original_line = None;
    side = None;
    reactions = None;
    body_html = None;
    body_text = None;
}

