(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Short_branch.t : Short Branch
 *)

type t = {
    name: string;
    commit: Short_branch_commit.t;
    protected: bool;
    protection: Branch_protection.t option [@default None];
    protection_url: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Short Branch *)
let create (name : string) (commit : Short_branch_commit.t) (protected : bool) : t = {
    name = name;
    commit = commit;
    protected = protected;
    protection = None;
    protection_url = None;
}

