(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Status_check_policy.t : Status Check Policy
 *)

type t = {
    url: string;
    strict: bool;
    contexts: string list;
    contexts_url: string;
} [@@deriving yojson { strict = false }, show ];;

(** Status Check Policy *)
let create (url : string) (strict : bool) (contexts : string list) (contexts_url : string) : t = {
    url = url;
    strict = strict;
    contexts = contexts;
    contexts_url = contexts_url;
}

