(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let codes_of_conduct_get_all_codes_of_conduct () =
  let open Lwt in
  let uri = Request.build_uri "/codes_of_conduct" in
  let headers = Request.default_headers in
  Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
  Request.read_json_body_as_list_of
    (JsonSupport.unwrap Code_of_conduct.of_yojson)
    resp body

let codes_of_conduct_get_conduct_code ~key =
  let open Lwt in
  let uri = Request.build_uri "/codes_of_conduct/{key}" in
  let headers = Request.default_headers in
  let uri = Request.replace_path_param uri "key" (fun x -> x) key in
  Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
  Request.read_json_body_as
    (JsonSupport.unwrap Code_of_conduct.of_yojson)
    resp body

let codes_of_conduct_get_for_repo ~owner ~repo =
  let open Lwt in
  let uri =
    Request.build_uri "/repos/{owner}/{repo}/community/code_of_conduct"
  in
  let headers = Request.default_headers in
  let uri = Request.replace_path_param uri "owner" (fun x -> x) owner in
  let uri = Request.replace_path_param uri "repo" (fun x -> x) repo in
  Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
  Request.read_json_body_as
    (JsonSupport.unwrap Code_of_conduct.of_yojson)
    resp body
