(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Whether Stripe automatically declines charges with an incorrect ZIP or postal code. This setting only applies when a ZIP or postal code is provided and they fail bank verification. *)
  avs_failure : bool;
  (* Whether Stripe automatically declines charges with an incorrect CVC. This setting only applies when a CVC is provided and it fails bank verification. *)
  cvc_failure : bool;
}
[@@deriving yojson { strict = false }, show]

let create (avs_failure : bool) (cvc_failure : bool) : t =
  { avs_failure; cvc_failure }
