(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Amount for bank account. *)
  bank_account : int32 option; [@default None]
  (* Amount for card. *)
  card : int32 option; [@default None]
  (* Amount for FPX. *)
  fpx : int32 option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t = { bank_account = None; card = None; fpx = None }
