(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  card_present : Payment_method_details_card_present.t option; [@default None]
  (* The type of payment method transaction-specific details from the transaction that generated this `card` payment method. Always `card_present`. *)
  _type : string;
}
[@@deriving yojson { strict = false }, show]

let create (_type : string) : t = { card_present = None; _type }
