(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* If `type` is `\''exact\''`, `date` will be the expected delivery date in the format YYYY-MM-DD. *)
  date : string option; [@default None]
  (* If `type` is `\''range\''`, `earliest` will be be the earliest delivery date in the format YYYY-MM-DD. *)
  earliest : string option; [@default None]
  (* If `type` is `\''range\''`, `latest` will be the latest delivery date in the format YYYY-MM-DD. *)
  latest : string option; [@default None]
  (* The type of estimate. Must be either `\''range\''` or `\''exact\''`. *)
  _type : string;
}
[@@deriving yojson { strict = false }, show]

let create (_type : string) : t =
  { date = None; earliest = None; latest = None; _type }
