(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Date by which evidence must be submitted in order to successfully challenge dispute. Will be null if the customer's bank or credit card company doesn't allow a response for this particular dispute. *)
  due_by : int32 option; [@default None]
  (* Whether evidence has been staged for this dispute. *)
  has_evidence : bool;
  (* Whether the last evidence submission was submitted past the due date. Defaults to `false` if no evidence submissions have occurred. If `true`, then delivery of the latest evidence is *not* guaranteed. *)
  past_due : bool;
  (* The number of times evidence has been submitted. Typically, you may only submit evidence once. *)
  submission_count : int32;
}
[@@deriving yojson { strict = false }, show]

let create (has_evidence : bool) (past_due : bool) (submission_count : int32) :
    t =
  { due_by = None; has_evidence; past_due; submission_count }
