(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Time at which the object was created. Measured in seconds since the Unix epoch. *)
  created : int32;
  (* Time at which the key will expire. Measured in seconds since the Unix epoch. *)
  expires : int32;
  (* Unique identifier for the object. *)
  id : string;
  (* Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode. *)
  livemode : bool;
  (* String representing the object's type. Objects of the same type share the same value. *)
  _object : Enums.ephemeral_key_object; [@default `Ephemeral_key]
  (* The key's secret. You can use this value to make authorized requests to the Stripe API. *)
  secret : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create (created : int32) (expires : int32) (id : string) (livemode : bool)
    (_object : Enums.ephemeral_key_object) : t =
  { created; expires; id; livemode; _object; secret = None }
