(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* (ID of a [file upload](https://stripe.com/docs/guides/file-upload)) Additional documentation supporting the dispute. *)
  additional_documentation : Any_ofstringfile.t option; [@default None]
  (* (ID of a [file upload](https://stripe.com/docs/guides/file-upload)) Copy of the card statement showing that the product had already been paid for. *)
  card_statement : Any_ofstringfile.t option; [@default None]
  (* (ID of a [file upload](https://stripe.com/docs/guides/file-upload)) Copy of the receipt showing that the product had been paid for in cash. *)
  cash_receipt : Any_ofstringfile.t option; [@default None]
  (* (ID of a [file upload](https://stripe.com/docs/guides/file-upload)) Image of the front and back of the check that was used to pay for the product. *)
  check_image : Any_ofstringfile.t option; [@default None]
  (* Explanation of why the cardholder is disputing this transaction. *)
  explanation : string option; [@default None]
  (* Transaction (e.g., ipi_...) that the disputed transaction is a duplicate of. Of the two or more transactions that are copies of each other, this is original undisputed one. *)
  original_transaction : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    additional_documentation = None;
    card_statement = None;
    cash_receipt = None;
    check_image = None;
    explanation = None;
    original_transaction = None;
  }
