(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = { (* The amount discounted. *)
           amount : int32; discount : Discount.t }
[@@deriving yojson { strict = false }, show]

let create (amount : int32) (discount : Discount.t) : t = { amount; discount }
