(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Time at which the object was created. Measured in seconds since the Unix epoch. *)
  created : int32;
  (* String representing the object's type. Objects of the same type share the same value. *)
  _object : Enums.login_link_object; [@default `Login_link]
  (* The URL for the login link. *)
  url : string;
}
[@@deriving yojson { strict = false }, show]

let create (created : int32) (_object : Enums.login_link_object) (url : string)
    : t =
  { created; _object; url }
