(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Type of entity that holds the account. This can be either `individual` or `company`. *)
  account_holder_type : Enums.issuing_cardholder_type option; [@default None]
  (* Name of the bank associated with the bank account. *)
  bank_name : string option; [@default None]
  (* Two-letter ISO code representing the country the bank account is located in. *)
  country : string option; [@default None]
  (* Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same. *)
  fingerprint : string option; [@default None]
  (* Last four digits of the bank account number. *)
  last4 : string option; [@default None]
  (* Routing transit number of the bank account. *)
  routing_number : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    account_holder_type = None;
    bank_name = None;
    country = None;
    fingerprint = None;
    last4 = None;
    routing_number = None;
  }
