(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Whether the person is a director of the account's legal entity. Currently only required for accounts in the EU. Directors are typically members of the governing board of the company, or responsible for ensuring the company meets its regulatory obligations. *)
  director : bool option; [@default None]
  (* Whether the person has significant responsibility to control, manage, or direct the organization. *)
  executive : bool option; [@default None]
  (* Whether the person is an owner of the account’s legal entity. *)
  owner : bool option; [@default None]
  (* The percent owned by the person of the account's legal entity. *)
  percent_ownership : float option; [@default None]
  (* Whether the person is authorized as the primary representative of the account. This is the person nominated by the business to provide information about themselves, and general information about the account. There can only be one representative at any given time. At the time the account is created, this person should be set to the person responsible for opening the account. *)
  representative : bool option; [@default None]
  (* The person's title (e.g., CEO, Support Engineer). *)
  title : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    director = None;
    executive = None;
    owner = None;
    percent_ownership = None;
    representative = None;
    title = None;
  }
