(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Monetary threshold that triggers the subscription to create an invoice *)
  amount_gte : int32 option; [@default None]
  (* Indicates if the `billing_cycle_anchor` should be reset when a threshold is reached. If true, `billing_cycle_anchor` will be updated to the date/time the threshold was last reached; otherwise, the value will remain unchanged. This value may not be `true` if the subscription contains items with plans that have `aggregate_usage=last_ever`. *)
  reset_billing_cycle_anchor : bool option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t = { amount_gte = None; reset_billing_cycle_anchor = None }
