(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Tax_i_ds_list_1.t : The customer's tax IDs.
 *)

type t = {
  (* Details about each object. *)
  data : Tax_id.t list;
  (* True if this list has another page of items after this one that can be fetched. *)
  has_more : bool;
  (* String representing the object's type. Objects of the same type share the same value. Always has the value `list`. *)
  _object : Enums.listaccountcapability_object; [@default `List]
  (* The URL where this list can be accessed. *)
  url : string;
}
[@@deriving yojson { strict = false }, show]

(** The customer's tax IDs. *)
let create (data : Tax_id.t list) (has_more : bool)
    (_object : Enums.listaccountcapability_object) (url : string) : t =
  { data; has_more; _object; url }
