(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The status of the BECS Direct Debit (AU) payments capability of the account, or whether the account can directly process BECS Direct Debit (AU) charges. *)
  au_becs_debit_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the Bacs Direct Debits payments capability of the account, or whether the account can directly process Bacs Direct Debits charges. *)
  bacs_debit_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the Bancontact payments capability of the account, or whether the account can directly process Bancontact charges. *)
  bancontact_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the card issuing capability of the account, or whether you can use Issuing to distribute funds on cards *)
  card_issuing : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the card payments capability of the account, or whether the account can directly process credit and debit card charges. *)
  card_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the Cartes Bancaires payments capability of the account, or whether the account can directly process Cartes Bancaires card charges in EUR currency. *)
  cartes_bancaires_payments : Enums.au_becs_debit_payments option;
      [@default None]
  (* The status of the EPS payments capability of the account, or whether the account can directly process EPS charges. *)
  eps_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the FPX payments capability of the account, or whether the account can directly process FPX charges. *)
  fpx_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the giropay payments capability of the account, or whether the account can directly process giropay charges. *)
  giropay_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the GrabPay payments capability of the account, or whether the account can directly process GrabPay charges. *)
  grabpay_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the iDEAL payments capability of the account, or whether the account can directly process iDEAL charges. *)
  ideal_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the JCB payments capability of the account, or whether the account (Japan only) can directly process JCB credit card charges in JPY currency. *)
  jcb_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the legacy payments capability of the account. *)
  legacy_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the OXXO payments capability of the account, or whether the account can directly process OXXO charges. *)
  oxxo_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the P24 payments capability of the account, or whether the account can directly process P24 charges. *)
  p24_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the SEPA Direct Debits payments capability of the account, or whether the account can directly process SEPA Direct Debits charges. *)
  sepa_debit_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the Sofort payments capability of the account, or whether the account can directly process Sofort charges. *)
  sofort_payments : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the tax reporting 1099-K (US) capability of the account. *)
  tax_reporting_us_1099_k : Enums.au_becs_debit_payments option; [@default None]
  (* The status of the tax reporting 1099-MISC (US) capability of the account. *)
  tax_reporting_us_1099_misc : Enums.au_becs_debit_payments option;
      [@default None]
  (* The status of the transfers capability of the account, or whether your platform can transfer funds to the account. *)
  transfers : Enums.au_becs_debit_payments option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    au_becs_debit_payments = None;
    bacs_debit_payments = None;
    bancontact_payments = None;
    card_issuing = None;
    card_payments = None;
    cartes_bancaires_payments = None;
    eps_payments = None;
    fpx_payments = None;
    giropay_payments = None;
    grabpay_payments = None;
    ideal_payments = None;
    jcb_payments = None;
    legacy_payments = None;
    oxxo_payments = None;
    p24_payments = None;
    sepa_debit_payments = None;
    sofort_payments = None;
    tax_reporting_us_1099_k = None;
    tax_reporting_us_1099_misc = None;
    transfers = None;
  }
