(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The amount of `currency` that the transaction was converted to in real-time. *)
  amount : int32;
  (* The amount of bitcoin contained in the transaction. *)
  bitcoin_amount : int32;
  (* Time at which the object was created. Measured in seconds since the Unix epoch. *)
  created : int32;
  (* Three-letter [ISO code for the currency](https://stripe.com/docs/currencies) to which this transaction was converted. *)
  currency : string;
  (* Unique identifier for the object. *)
  id : string;
  (* String representing the object's type. Objects of the same type share the same value. *)
  _object : Enums.bitcoin_transaction_object; [@default `Bitcoin_transaction]
  (* The receiver to which this transaction was sent. *)
  receiver : string;
}
[@@deriving yojson { strict = false }, show]

let create (amount : int32) (bitcoin_amount : int32) (created : int32)
    (currency : string) (id : string)
    (_object : Enums.bitcoin_transaction_object) (receiver : string) : t =
  { amount; bitcoin_amount; created; currency; id; _object; receiver }
