(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Error.t : An error response from the Stripe API
 *)

type t = { error : Api_errors.t } [@@deriving yojson { strict = false }, show]

(** An error response from the Stripe API *)
let create (error : Api_errors.t) : t = { error }
