(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema External_account_list_1.t : External accounts (bank accounts and debit cards) currently attached to this account
 *)

type t = {
  (* The list contains all external accounts that have been attached to the Stripe account. These may be bank accounts or cards. *)
  data : Any_ofbank_accountcard.t list;
  (* True if this list has another page of items after this one that can be fetched. *)
  has_more : bool;
  (* String representing the object's type. Objects of the same type share the same value. Always has the value `list`. *)
  _object : Enums.listaccountcapability_object; [@default `List]
  (* The URL where this list can be accessed. *)
  url : string;
}
[@@deriving yojson { strict = false }, show]

(** External accounts (bank accounts and debit cards) currently attached to this account *)
let create (data : Any_ofbank_accountcard.t list) (has_more : bool)
    (_object : Enums.listaccountcapability_object) (url : string) : t =
  { data; has_more; _object; url }
