(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The count of inventory available. Will be present if and only if `type` is `finite`. *)
  quantity : int32 option; [@default None]
  (* Inventory type. Possible values are `finite`, `bucket` (not quantified), and `infinite`. *)
  _type : string;
  (* An indicator of the inventory available. Possible values are `in_stock`, `limited`, and `out_of_stock`. Will be present if and only if `type` is `bucket`. *)
  value : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create (_type : string) : t = { quantity = None; _type; value = None }
