(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Default custom fields to be displayed on invoices for this customer. *)
  custom_fields : Invoice_setting_custom_field.t list;
  (* ID of a payment method that's attached to the customer, to be used as the customer's default payment method for subscriptions and invoices. *)
  default_payment_method : Any_ofstringpayment_method.t option; [@default None]
  (* Default footer to be displayed on invoices for this customer. *)
  footer : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  { custom_fields = []; default_payment_method = None; footer = None }
