(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The IDs of the line items that triggered the threshold invoice. *)
  line_item_ids : string list;
  (* The quantity threshold boundary that applied to the given line item. *)
  usage_gte : int32;
}
[@@deriving yojson { strict = false }, show]

let create (line_item_ids : string list) (usage_gte : int32) : t =
  { line_item_ids; usage_gte }
