(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* An array of two-letter ISO country codes representing which countries Checkout should provide as options for shipping locations. Unsupported country codes: `AS, CX, CC, CU, HM, IR, KP, MH, FM, NF, MP, PW, SD, SY, UM, VI`. *)
  allowed_countries : Enums.allowed_countries list;
}
[@@deriving yojson { strict = false }, show]

let create (allowed_countries : Enums.allowed_countries list) : t =
  { allowed_countries }
