(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* This is the sum of all the line item discounts. *)
  amount_discount : int32;
  (* This is the sum of all the line item tax amounts. *)
  amount_tax : int32;
  breakdown :
    Payment_pages_checkout_session_total_details_resource_breakdown.t option;
      [@default None]
}
[@@deriving yojson { strict = false }, show]

let create (amount_discount : int32) (amount_tax : int32) : t =
  { amount_discount; amount_tax; breakdown = None }
