(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Installment plan selected for the payment. *)
  plan : Any_ofpayment_method_details_card_installments_plan.t option;
      [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t = { plan = None }
