(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = { _end : int32; start : int32 }
[@@deriving yojson { strict = false }, show]

let create (_end : int32) (start : int32) : t = { _end; start }
