(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  application_cryptogram : string option; [@default None]
  application_preferred_name : string option; [@default None]
  authorization_code : string option; [@default None]
  authorization_response_code : string option; [@default None]
  brand : string option; [@default None]
  country : string option; [@default None]
  cvm_type : string option; [@default None]
  data_type : string option; [@default None]
  dedicated_file_name : string option; [@default None]
  emv_auth_data : string option; [@default None]
  evidence_customer_signature : string option; [@default None]
  evidence_transaction_certificate : string option; [@default None]
  exp_month : int32 option; [@default None]
  exp_year : int32 option; [@default None]
  fingerprint : string option; [@default None]
  funding : string option; [@default None]
  last4 : string option; [@default None]
  pos_device_id : string option; [@default None]
  pos_entry_mode : string option; [@default None]
  read_method : string option; [@default None]
  reader : string option; [@default None]
  terminal_verification_results : string option; [@default None]
  transaction_status_information : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    application_cryptogram = None;
    application_preferred_name = None;
    authorization_code = None;
    authorization_response_code = None;
    brand = None;
    country = None;
    cvm_type = None;
    data_type = None;
    dedicated_file_name = None;
    emv_auth_data = None;
    evidence_customer_signature = None;
    evidence_transaction_certificate = None;
    exp_month = None;
    exp_year = None;
    fingerprint = None;
    funding = None;
    last4 = None;
    pos_device_id = None;
    pos_entry_mode = None;
    read_method = None;
    reader = None;
    terminal_verification_results = None;
    transaction_status_information = None;
  }
