(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  entity : string option; [@default None]
  reference : string option; [@default None]
  refund_account_holder_address_city : string option; [@default None]
  refund_account_holder_address_country : string option; [@default None]
  refund_account_holder_address_line1 : string option; [@default None]
  refund_account_holder_address_line2 : string option; [@default None]
  refund_account_holder_address_postal_code : string option; [@default None]
  refund_account_holder_address_state : string option; [@default None]
  refund_account_holder_name : string option; [@default None]
  refund_iban : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    entity = None;
    reference = None;
    refund_account_holder_address_city = None;
    refund_account_holder_address_country = None;
    refund_account_holder_address_line1 = None;
    refund_account_holder_address_line2 = None;
    refund_account_holder_address_postal_code = None;
    refund_account_holder_address_state = None;
    refund_account_holder_name = None;
    refund_iban = None;
  }
