(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Customer data associated with the transfer. *)
  customer_data : string option; [@default None]
  (* Bank account fingerprint associated with the transfer. *)
  fingerprint : string option; [@default None]
  (* Last 4 digits of the account number associated with the transfer. *)
  last4 : string option; [@default None]
  (* Routing number associated with the transfer. *)
  routing_number : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    customer_data = None;
    fingerprint = None;
    last4 = None;
    routing_number = None;
  }
