(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Divide usage by this number. *)
  divide_by : int32;
  (* After division, either round the result `up` or `down`. *)
  round : Enums.round;
}
[@@deriving yojson { strict = false }, show]

let create (divide_by : int32) (round : Enums.round) : t = { divide_by; round }
