(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Unique identifier for the object. *)
  id : string;
  (* The invoice in which this usage period has been billed for. *)
  invoice : string option; [@default None]
  (* Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode. *)
  livemode : bool;
  (* String representing the object's type. Objects of the same type share the same value. *)
  _object : Enums.usage_record_summary_object; [@default `Usage_record_summary]
  period : Period.t;
  (* The ID of the subscription item this summary is describing. *)
  subscription_item : string;
  (* The total usage within this usage period. *)
  total_usage : int32;
}
[@@deriving yojson { strict = false }, show]

let create (id : string) (livemode : bool)
    (_object : Enums.usage_record_summary_object) (period : Period.t)
    (subscription_item : string) (total_usage : int32) : t =
  {
    id;
    invoice = None;
    livemode;
    _object;
    period;
    subscription_item;
    total_usage;
  }
